### PR TITLE
Fix MixerTTS generate_spectrogram types and dimensions

### PR DESCRIPTION
**Pull request by m-toman**
Fixes the typecheck decorator for generate_spectrogram in MixerTTS and the swapping melspec and time dimension (as also done here https://github.com/NVIDIA/NeMo/blob/3687f2eaae36de6dd686caa99d2fe3100a5f4431/nemo/collections/tts/models/mixer_tts.py#L649)

You're probably in the middle of a refactor so sorry if you already got that, @Oktai15  (?)

(just FYI, I just trained MixerTTS from LJ with the current main head and everything worked fine, except this transpose missing when synthesizing and the mismatch of the decorator with the parameters)

### CODE REVIEW

**Review by Oktai15 — APPROVED** [review]

**Comment by m-toman** [comment]
Unfortunately can't check what CI is complaining about ;)

**Comment by m-toman** [comment]
Getting 
``` 
The workflow is not valid. .github/workflows/blossom-ci.yml (Line: 36, Col: 9): Unrecognized named-value: 'okuchaiev'. Located at position 42 within expression: contains( 'ravitestgit,', format('{0},', okuchaiev)) && 
github.event.comment.body == '/blossom-ci' 
```


Seems to be related to this commit: https://github.com/NVIDIA/NeMo/commit/3cf0af6d640793383e731c5a6a341055ebd64ea9

**Comment by Oktai15** [comment]
Closed. See https://github.com/NVIDIA/NeMo/pull/3330.

**Comment by m-toman** [comment]
Thanks, anything I should do differently in future when submitting a PR?

**Comment by Oktai15** [comment]
@m-toman, you were right, we needed to fix the problem with CI. This commit fixed the problem: https://github.com/NVIDIA/NeMo/commit/a5cd21eda0feeb0b55085f390252ccb181661e7d.

**Pull request closed without merging**
