### PR TITLE
Add ASR context-biasing tutorial

### PR DESCRIPTION
**Pull request by andrusenkoau**
# What does this PR do ?

Add a context-biasing tutorial (based on CTC-WS method) for CTC and RNN-T models.

**Collection**: [ASR]

# Changelog 
- Add tutorials/asr/ASR_Context_Biasing.ipynb tutorial

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by artbataev — COMMENTED** [review]
Overall looks good.

Several suggestions:
1) `hybrid_ctc_rnnt_model` is loaded but seems to be unnecessary. The last section uses `ctc_model` decoding, but `word_tokenization = hybrid_ctc_rnnt_model.tokenizer.text_to_tokens(word)` and some other statements use `hybrid_ctc_rnnt_model`, which is confusing (and maybe incorrect, but I think that due to same tokenizers in these models this works). Please, clarify/fix this.

2) `asr_model` is undefined in the last section, the statement `pred_text = asr_model.wer.decoding.ctc_decoder_predictions_tensor(greedy_predicts)[0][0]` itself requires comments/prints. 

3) Maybe it is worth installing graphviz for google colab directly (if `IN_COLAB`...)

4) I did not see any bold/blue arcs in the graph. Is this fine?
Screenshot 2024-03-13 at 23 51 20

5) Just a suggestion: the easiest way to check if you are using Google Colab is
```python
try:
    import google.colab
    IN_COLAB = True
except (ImportError, ModuleNotFoundError):
    IN_COLAB = False
```

6) Small typos
- `num_of_occurance` -> `num_of_occurrence(s)`
- "analyze regontion the accuracy of specific words" -> "analyze the recognition accuracy ..."

**Comment by andrusenkoau** [comment]
@artbataev thank you so much for the review!

About your suggestions/comments:

1. Done
2. Done
3. I leaved installing graphviz optional. The installation takes 5-10 minutes during which the window may become glitchy.
4. I made a fix, but it works only on my remote desktop. I do not know why Google Colab does not display the right colors. I removed comments about colors.
5. Done
6. Done
7. Done

**Comment by andrusenkoau** [comment]
jenkins

**Review by artbataev — APPROVED** [review]
Thank you!

**Pull request merged**
