### PR TITLE
Test data dir

### PR DESCRIPTION
**Pull request by tkornuta-nvidia**
The PR aims at the problem of storing test (binary) data in NeMo soure code.

The solution involves:
 - [x] storing binary data as part of nemo release files, currently set to:
https://github.com/NVIDIA/NeMo/releases/tag/v0.11.0 -> `test_data.tar.gz`
 - [x] pytest_configure() method which:
    * checks if `test_data.tar.gz` is present in `tests/.data`
      * if so, compares its size with github's `test_data.tar.gz`
    * if absent or sizes not equal - downloads the archive from github and unpacks it
 - [x] new `test_data_dir` fixture providing the absolute path to the test data
 - [x] `test_test_data_dir` unit test testing the presence of test data/showing how to use the `test_data_dir` fixture

Currently all the variables are "hardcoded in `conftest.py`:
```
# Those variables probably should go to main NeMo configuration file (config.yaml).
__TEST_DATA_FILENAME = "test_data.tar.gz"
__TEST_DATA_URL = "https://github.com/NVIDIA/NeMo/releases/download/v0.11.0/"
__TEST_DATA_SUBDIR = ".data"
```

### CODE REVIEW

**Comment by blisc** [comment]
Shouldn't this PR also remove all test data that is currently in the branch?

**Comment by tkornuta-nvidia** [comment]
> Shouldn't this PR also remove all test data that is currently in the branch?

I am leaving that up to you, guys.

**Comment by tkornuta-nvidia** [comment]
> ou add documentation to the dev guide regarding this and an example (from old Nemo repo)

Adding some kind of a description of this solution (once merged) for sure makes sense, not sure what do you mean by "from old NeMo repo" though...

**Comment by blisc** [comment]
> > Shouldn't this PR also remove all test data that is currently in the branch?
> 
> I am leaving that up to you, guys.

I am in support of removing. @okuchaiev @titu1994 @ericharper any objections?

**Comment by tkornuta-nvidia** [comment]
> > > Shouldn't this PR also remove all test data that is currently in the branch?
> > 
> > 
> > I am leaving that up to you, guys.
> 
> I am in support of removing. @okuchaiev @titu1994 @ericharper any objections?

To be precise: I want the folder/data from tests/data to be removed too. But I want the people, who are implementing those tests, to remove their data from the folder/add it to the archive on their own.

**Comment by blisc** [comment]
> > > > Shouldn't this PR also remove all test data that is currently in the branch?
> > > 
> > > 
> > > I am leaving that up to you, guys.
> > 
> > 
> > I am in support of removing. @okuchaiev @titu1994 @ericharper any objections?
> 
> To be precise: I want the folder/data from tests/data to be removed too. But I want the people, who are implementing those tests, to remove their data from the folder/add it to the archive on their own.

Oh I see. I misunderstood. Then IMO, we should go through whoever has data in the repo, create a jira ticket for each one, and assign them. This should be low priority for NeMo 1.0 beta/RC1, but high priority for NeMo 1.0.

I'd let @okuchaiev make the final call here on the process, and on who should create the jira tickets.

**Comment by titu1994** [comment]
From old nemo data > take one of the data dependent test from old Nemo, port it to use this fixture and show it in the dev doc. So that people know exactly how to use it.

I too support removing all the data from the tests dir. Leaving it to others likely means it will cause multiple prs to patch parts of tests. Better do it in one go

**Comment by okuchaiev** [comment]
there is one file there (tests/data/m_common.model) - let's merge this and ask that person to redo their test.

**Comment by tkornuta-nvidia** [comment]
> there is one file there (tests/data/m_common.model) - let's merge this and ask that person to redo their test.

hmmm, but this doesn't even look like a data file...

which raises another question: how about some data, not being the actual "test data"?

Exemplary use-case:
In acceptance we could need checkpoints/pre-trained weights to tests check if model still returns a correct prediction for a given input.

Should they be downloaded from NGC? Or maybe for the ones used in tests we should store them similarly to test data?

**Comment by titu1994** [comment]
Yes, in Keras they hold most of the old HDFS checkpoint filed into the release tab. They use different files of course for this purpose, since each checkpoint was in essence a binary blob. 

I think doing that kind of test is quite expensive - many of the checkpoint are several GB in size. To perform a full scale download and cache for all of them would consume too much time of the CI + it would take a lot of space too.

**Comment by titu1994** [comment]
I'll note that Keras does **not** perform acceptance tests on any of it's weight files, they are only used as a source of data for a local copy of the model when a user tried to instantiate with the pretrained=Imagenet argument

**Pull request merged**
