### PR TITLE
Fix mcore conversion bug

### PR DESCRIPTION
**Pull request by cuichenx**
# What does this PR do ?

Fix mcore conversion script bug which affected GPT3 models. Also improve the UX of the script.

**Collection**: NLP

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
python scripts/nlp_language_modeling/convert_nemo_gpt_to_mcore.py --in-folder=<input-nemo-folder> --out-file=<output-mcore-ckpt>

```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to #7730

### CODE REVIEW

**Review by aklife97 — APPROVED** [review]
LGTM, thank you!

**Comment by aklife97** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Review by aklife97 — APPROVED** [review]

**Comment by aklife97** [comment]
jenkins

**Pull request merged**
