### PR TITLE
Flatten pl.trainer to trainer

### PR DESCRIPTION
**Pull request by ericharper**
We should flatten pl.trainer to trainer.

Updated all examples.

### CODE REVIEW

**Comment by okuchaiev** [comment]
is this still WIP?

**Comment by titu1994** [comment]
I wonder, won't editing all the files at once cause merge conflicts with basically every PR out there currently ? Would it be better to default to pl.*, But temporarily inject a copy of pl under PL.trainer for compat with older code + manifests and then let individual pic update their code ? Just a thought.

**Comment by titu1994** [comment]
@ericharper @okuchaiev I assumed we are keeping the "pl" namespace and dripping the "trainer" part. What's the benefit of dropping 3 chars vs dropping the verbose "trainer"?

**Comment by ericharper** [comment]
> is this still WIP?

Just waiting on https://github.com/NVIDIA/NeMo/pull/896

**Comment by ericharper** [comment]
> @ericharper @okuchaiev I assumed we are keeping the "pl" namespace and dropping the "trainer" part. What's the benefit of dropping 3 chars vs dropping the verbose "trainer"?

This works with multiple trainer default setups and multiple trainers. User can have /conf/trainer/1.yaml, /conf/trainer/2.yaml

**Pull request merged**
