### PR TITLE
Adding jasper_tune.py for tuning of ASR hyper parameters alpha and beta

### PR DESCRIPTION
**Pull request by harisankarh**
This will help in selecting the appropriate alpha and beta parameters for a given validation set (similar to `tune.py` in Deepspeech2).

Signed-off-by: Hariankar H <harisankarh@gmail.com>

### CODE REVIEW

**Comment by okuchaiev** [comment]
I think this should just be merged with "examples/asr/jasper.py" @vsl9 and @blisc what do you think?

**Comment by vsl9** [comment]
Harisankar, thanks a lot for the PR!
I agree with Oleksii that instead of creating a new script it is worth to modify original `jasper_infer.py`.
Some nice things to add:
- `beam_width` parameter to override default 128
- `alpha_step`, `beta_step` parameters to define steps for grid search
- rename `alpha_from`/`beta_from` to just `alpha`/`beta` so that it is possible to do inference with a single set of alpha/beta values (without tuning over a grid)
There is a similar script in our OpenSeq2Seq project: https://github.com/NVIDIA/OpenSeq2Seq/blob/master/scripts/decode.py
It would be great to implement a similar command line API with `beam_width`, `alpha`, `alpha_max`, `alpha_step`, `beta`, `beta_max`, `beta_step` in `jasper_infer.py` to support a single inference or tuning.

**Comment by harisankarh** [comment]
Thanks for the feedback. I'll look into it.

**Comment by harisankarh** [comment]
@vsl9 I've made the changes you suggested. Created fresh pull request [https://github.com/NVIDIA/NeMo/pull/67](#67).

Closing this pull request

**Pull request closed without merging**
