### PR TITLE
Speaker diarization

### PR DESCRIPTION
**Pull request by nithinraok**
This PR enables speaker diarization inference capability in NeMo. It features and supports both oracle and non-oracle VAD diarization with spectral clustering. 

Here are some of the new additions made:

- Adds support to diarize wav files given through list or from a file containing paths to audio files (speaker_diarize.py)
- Added ClusteringDiarizer model that combines VAD and Speaker Embeddings model to extract time stamps and Embeddings (clustering_diarizer.py)
- Added VAD utils to support overlap segment creation and probability smoothing for combining VAD decisions (vad_utils.py)
- Added script to get best thresholds for unseen data given through dev manifest. (vad_tune_threshold.py) 
- Added utils to clean and combine time stamps from VAD. (speaker_utils.py)
- Perform clustering and writes predicted rttm (speaker_utils.py)
- Added rttm_to_manifest.py to create oracle manifest for performing diarization with any external VAD decision

### CODE REVIEW

**Review by okuchaiev — APPROVED** [review]
looks good to me

**Comment by okuchaiev** [comment]
looks good to me, @fayejf and @jbalam-nv  could you please have a look too?

**Review by jbalam-nv — APPROVED** [review]
LGTM

**Review by fayejf — APPROVED** [review]
LGTM

**Pull request merged**
