### PR TITLE
Specify batch_size=1 to global_step log

### PR DESCRIPTION
**Pull request by piraka9011**
# What does this PR do ?

Explicitly specify `batch_size` for the `global_step` log.

Apparently, the call to `log` for the `global_step` metric in `ctc_models.py` sometimes fails with the following stack trace.

<details>
<summary>Stacktrace</summary>

```
Traceback (most recent call last):
  File "/home/msis/tdreeb/train.py", line 67, in main
    trainer.fit(asr_model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 241, in on_advance_end
    self._run_validation()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 299, in _run_validation
    self.val_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 358, in validation_step
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 987, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 90, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 641, in validation_step
    self.log('global_step', torch.tensor(self.trainer.global_step, dtype=torch.float32))
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 487, in log
    results.log(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 493, in log
    batch_size = self._extract_batch_size(self[key], batch_size, meta)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 428, in _extract_batch_size
    batch_size = extract_batch_size(self.batch)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 107, in extract_batch_size
    raise MisconfigurationException(error_msg)
pytorch_lightning.utilities.exceptions.MisconfigurationException: We could not infer the batch_size from the batch. Either simplify its structure or provide the batch_size as `self.log(..., batch_size=batch_size)`.
```

</details>

I'm unsure if this points to an underlying issue w/ PTL or the `global_step` param, but this change resolves the issue.

**Collection**: ASR

# Changelog 

- Explicitly specify `batch_size` for the `global_step` log.

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [X] Did you write any new necessary tests?
- [X] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [X] Bugfix
- [ ] Documentation

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

### CODE REVIEW

**Comment by titu1994** [comment]
This should no longer be required to be logged now that wandb has fixed it's on logging in ptl.

**Comment by msis** [comment]
Error log:
```
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 697, in fit                        
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path                                            File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt     return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)                                           
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch                                                                                                                             
    return function(*args, **kwargs)                                                                                            File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl                  
    results = self._run(model, ckpt_path=self.ckpt_path)                                                                        File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run                      
    results = self._run_stage()                                                                                               
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage                
    return self._run_train()                                                                                                  
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train                    self.fit_loop.run()                                                                                                         File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 200, in run                                 self.advance(*args, **kwargs)                                                                                               File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance                         self._outputs = self.epoch_loop.run(self._data_fetcher)                                                                   
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 201, in run                             
    self.on_advance_end()                                                                                                     
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 241, in on_advance_
end                                                                                                                           
    self._run_validation()                                                                                                    
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 299, in _run_valida
tion                                                                                                                          
    self.val_loop.run()                                                                                                       
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 200, in run                             
    self.advance(*args, **kwargs)                                                                                             
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance   
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)                                              
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 200, in run                             
    self.advance(*args, **kwargs)                                                                                             
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance  
    output = self._evaluation_step(**kwargs)                                                                                  
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluati
on_step                                                                                                                       
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())                                                    
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook       
    output = fn(*args, **kwargs)                                                                                              
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/strategies/ddp.py", line 358, in validation_step                 return self.model(*args, **kwargs)                                                                                        
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl                          
    return forward_call(*input, **kwargs)                                                                                     
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward                       
    output = self._run_ddp_forward(*inputs, **kwargs)                                                                         
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward               
    return module_to_run(*inputs[0], **kwargs[0])                                                                             
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl                          
    return forward_call(*input, **kwargs)                                                                                     
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 90, in forward                      
    return self.module.validation_step(*inputs, **kwargs)                                                                     
  File "/opt/conda/lib/python3.7/site-packages/nemo/collections/asr/models/ctc_models.py", line 673, in validation_step       
    self.log('global_step', torch.tensor(self.trainer.global_step, dtype=torch.float32))                                      
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/module.py", line 503, in log                            
    rank_zero_only=rank_zero_only,
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 493, in 
log
    batch_size = self._extract_batch_size(self[key], batch_size, meta)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 428, in 
_extract_batch_size
    batch_size = extract_batch_size(self.batch)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/data.py", line 107, in extract_batch_size
    raise MisconfigurationException(error_msg)
pytorch_lightning.utilities.exceptions.MisconfigurationException: We could not infer the batch_size from the batch. Either sim
plify its structure or provide the batch_size as `self.log(..., batch_size=batch_size)`.
```

**Comment by msis** [comment]
Can this please be reviewed and merged?

**Comment by titu1994** [comment]
What version of nemo and ptl are you on? We have run dozens of experiments with Nemo 1.12 and 1.13 and not received this error. 

This is not a trivial change since we would need to update all ASR models with this same change if necessary, which in 1.12 and 1.13 does not seem to be the case c

**Comment by msis** [comment]
`pytorch_lightning` is at `1.7.7`.
It happens for both NeMo `1.12` and `1.13`.

It's running with `ddp` on 8xA100 40G.
Did you try with `ddp` as well and it worked?

**Comment by msis** [comment]
There are also many deprecation warnings that someone should have a look at.
This just might be one of the early dominoes to fall.

**Comment by titu1994** [comment]
Yes we only train on ddp. We're currently training with r1.13 as well as main and didn't face this. @nithinraok @SeanNaren did you see this?

**Pull request closed without merging**
