### PR TITLE
[TN] bugfix file handler is not closed.

### PR DESCRIPTION
**Pull request by XuesongYang**
Signed-off-by: Xuesong Yang <1646669+XuesongYang@users.noreply.github.com>

# What does this PR do ?

```
files are not closed so that memory may leak.
```
**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by yzhang123 — APPROVED** [review]
thanks!

**Comment by XuesongYang** [comment]
> thanks!

A second thought: is there a better place, a language-free utils/helper file, to host this function? these functions are exactly the same.

**Comment by yzhang123** [comment]
> > thanks!
> 
> @yzhang123 @ekmb A second thought: is there a better place, a language-free utils/helper file, to host this function? these functions are exactly the same.

This is a good idea. But TN/ITN has been migrated to new repo, so we should add the refactoring there. fyi @anand-nv

**Comment by XuesongYang** [comment]
> > > thanks!
> > 
> > 
> > @yzhang123 @ekmb A second thought: is there a better place, a language-free utils/helper file, to host this function? these functions are exactly the same.
> 
> This is a good idea. But TN/ITN has been migrated to new repo, so we should add the refactoring there. fyi @anand-nv

ok. Are you guys planning to merge any progress of TN here to the new repo?

**Pull request merged**
