### PR TITLE
Update results.rst for Canary Inference

### PR DESCRIPTION
**Pull request by stevehuang52**
# What does this PR do ?

Update results.rst for Canary Inference, please feel free to modify

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
Looks fantastic ! Thanks !

**Comment by titu1994** [comment]
Let me know if you want to fast merge after additional approvals

**Comment by stevehuang52** [comment]
jenkins

**Comment by stevehuang52** [comment]
@titu1994 could you please fast merge this?

**Comment by stevehuang52** [comment]
jenkins

**Comment by stevehuang52** [comment]
jenkins

**Comment by titu1994** [comment]
Docs changes does not need CI to pass, I can merge it if it's ready

**Pull request merged**
