### PR TITLE
Add FastConformer Hybrid ASR models for EN, ES, IT, DE, PL, HR, UA, BY

### PR DESCRIPTION
**Pull request by KunalDhawan**
# What does this PR do ?

This PR adds the FastConformer Hybrid ASR models (EN, ES, IT, DE, PL, BY, HR, UA) to the PreTrained models catalog

**Collection**: ASR

# Changelog 
- Added the FC Hybrid models to nemo/collections/asr/models/hybrid_rnnt_ctc_bpe_models.py
- Updated the ASR docs at NeMo/docs/source/asr/results.rst
- Created new results tables for BY (NeMo/docs/source/asr/data/benchmark_by.csv), UA (NeMo/docs/source/asr/data/benchmark_ua.csv)

# Usage
When loading pre-trained models, we can now specify:
- stt_en_fastconformer_hybrid_large_pc
- stt_de_fastconformer_hybrid_large_pc
- stt_it_fastconformer_hybrid_large_pc
- stt_es_fastconformer_hybrid_large_pc
- stt_hr_fastconformer_hybrid_large_pc
- stt_by_fastconformer_hybrid_large_pc
- stt_ua_fastconformer_hybrid_large_pc
- stt_pl_fastconformer_hybrid_large_pc
- stt_en_fastconformer_transducer_large
- stt_en_fastconformer_ctc_large

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by titu1994 — DISMISSED** [review]
Thank !

**Review by VahidooX — CHANGES_REQUESTED** [review]
Please update the following page:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/results.html

**Review by titu1994 — APPROVED** [review]
Fantastic thanks !

**Review by titu1994 — APPROVED** [review]

**Review by VahidooX — APPROVED** [review]
Thanks!

**Pull request merged**
