### PR TITLE
Distributed optimizer reduces GPT embedding grads in FP32

### PR DESCRIPTION
**Pull request by timmoon10**
# What does this PR do ?

When training Megatron-core GPT with the distributed optimizer, the embedding gradients were reduced in the grad sync dtype (usually BF16). However, we want to reduce in FP32 to improve convergence.

**Collection**: NLP

# Changelog 
- Make sure GPT embedding grads are reduced in FP32.

# Usage

Run GPT, e.g. with the config at https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/conf/megatron_gpt_config.yaml.

Enable mcore with `model.mcore_gpt=True` and the distributed optimizer with `model.optim.name=distributed_fused_adam`.

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* mcore support was added in https://github.com/NVIDIA/NeMo/pull/7093
* Distopt support for mixed grad dtypes was added in https://github.com/NVIDIA/NeMo/pull/5920

### CODE REVIEW

**Comment by timmoon10** [comment]
jenkins

**Comment by timmoon10** [comment]
jenkins

**Comment by timmoon10** [comment]
jenkins

**Comment by timmoon10** [comment]
jenkins

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Review by erhoo82 — APPROVED** [review]
LGTM given it gives the same convergence.

**Pull request merged**
