### PR TITLE
Integrating mcore export

### PR DESCRIPTION
**Pull request by shanmugamr1992**
# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by oyilmaz-nvidia — DISMISSED** [review]
LGTM.

**Comment by shanmugamr1992** [comment]
jenkins

**Comment by shanmugamr1992** [comment]
jenkins

**Review by oyilmaz-nvidia — APPROVED** [review]
LGTM.

**Comment by shanmugamr1992** [comment]
jenkins

**Comment by janekl** [comment]
We might also want to bump MCore commit [here](https://github.com/NVIDIA/NeMo/blob/5b88aaa82781d32b0e88b2a9b9976c6cf60d9bd2/Dockerfile.ci#L61C15-L61C55) to [45bf4c1821c2a87ca02e8a0377d61097bac92d07  ](https://github.com/NVIDIA/Megatron-LM/commit/45bf4c1821c2a87ca02e8a0377d61097bac92d07) so that it's clear how to use newly integrated code

**Review by oyilmaz-nvidia — APPROVED** [review]

**Review by pablo-garay — APPROVED** [review]

**Review by oyilmaz-nvidia — APPROVED** [review]

**Pull request merged**
