### PR TITLE
Fix Canary chunked infer on short audios

### PR DESCRIPTION
**Pull request by stevehuang52**
# What does this PR do ?

Fix Canary chunked infer on short audios. Previous version works badly on short audios since it pads short audios to the whole max_chunk length (e.g. 40s), while in this fix we allow the last chunk length to be less than the max_chunk

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
This looks good for now, thanks git finding the bug !

**Comment by titu1994** [comment]
Jenkins

**Review by pzelasko — APPROVED** [review]

**Review by nithinraok — DISMISSED** [review]

**Comment by stevehuang52** [comment]
jenkins

**Comment by stevehuang52** [comment]
jenkins

**Review by pzelasko — APPROVED** [review]
Asked some questions offline, happy with the answers -- LGTM

**Pull request merged**
