### PR TITLE
Fixed RadTTS unit test

### PR DESCRIPTION
**Pull request by borisfom**
Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>

# What does this PR do ?

It looks like (due to updates to internals?) RadTTS now requires a bit higher minimum length of the input.
I will investigate some more but that fix would unblock the test.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by XuesongYang** [comment]
LGTM. is it possible to merge to r1.14.0 followed by main, or manually merge to both branches? Thanks.

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Review by XuesongYang — APPROVED** [review]

**Comment by borisfom** [comment]
Main has this change already.

**Comment by XuesongYang** [comment]
> Main has this change already.

@borisfom could you pls elaborate this? r1.14.0 and main do not have such code changes. Thanks.

**Pull request merged**
