### PR TITLE
Fix adding positional embeddings in-place in FFTransformerDecoder

### PR DESCRIPTION
**Pull request by The0nix**
# What does this PR do ?

I believe this PR fixes the issue of FFTransformerDecoder altering the input tensor by adding positional embeddings in-place.

**Collection**: TTS

# Changelog 
- change `inp += pos_emb` to `inp = inp + pos_emb` to prevent changing the input tensor

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [X] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

### CODE REVIEW

**Review by hsiehjackson — COMMENTED** [review]
Thanks! LGTM!

**Review by XuesongYang — DISMISSED** [review]
LGTM after talking to @hsiehjackson .

**Comment by The0nix** [comment]
@XuesongYang, is something wrong?

**Comment by XuesongYang** [comment]
> @XuesongYang, is something wrong?

nothing wrong, just need to verify it. See below,
```
In [1]: import torch

In [2]: x = torch.randn(2, 5)

In [3]: y = torch.randn(2, 5)

In [4]: x
Out[4]:
tensor([[ 0.0275,  1.1197, -0.2925, -0.2620, -1.2882],
        [ 0.8825, -0.3293, -0.3481, -0.5064, -0.8700]])

In [5]: y
Out[5]:
tensor([[-1.6791, -0.1128, -1.3560, -1.2440,  0.2396],
        [ 0.9363,  1.1602, -0.9657, -0.4809,  1.0652]])

In [6]: z = x + y

In [7]: z
Out[7]:
tensor([[-1.6516,  1.0069, -1.6484, -1.5060, -1.0486],
        [ 1.8188,  0.8309, -1.3138, -0.9873,  0.1952]])

In [8]: tmp = x

In [9]: tmp
Out[9]:
tensor([[ 0.0275,  1.1197, -0.2925, -0.2620, -1.2882],
        [ 0.8825, -0.3293, -0.3481, -0.5064, -0.8700]])

In [10]: x += y

In [11]: x
Out[11]:
tensor([[-1.6516,  1.0069, -1.6484, -1.5060, -1.0486],
        [ 1.8188,  0.8309, -1.3138, -0.9873,  0.1952]])

In [12]: x == tmp
Out[12]:
tensor([[True, True, True, True, True],
        [True, True, True, True, True]])

In [13]: x = torch.randn(2, 5)

In [14]: y = torch.randn(2, 5)

In [15]: z = x + y

In [16]: x
Out[16]:
tensor([[ 0.0937, -0.0519, -1.5766, -0.7709, -2.5773],
        [ 1.1673,  1.9548,  0.9662, -0.2257,  1.3812]])

In [17]: y
Out[17]:
tensor([[-0.4613, -0.5194,  0.0889,  0.1225,  0.5598],
        [-0.3716,  0.5129,  0.3501, -0.4407,  1.5401]])

In [18]: z
Out[18]:
tensor([[-0.3675, -0.5714, -1.4877, -0.6484, -2.0176],
        [ 0.7957,  2.4677,  1.3163, -0.6664,  2.9213]])

In [19]: tmp = x

In [20]: tmp
Out[20]:
tensor([[ 0.0937, -0.0519, -1.5766, -0.7709, -2.5773],
        [ 1.1673,  1.9548,  0.9662, -0.2257,  1.3812]])

In [21]: x = x + y

In [22]: x
Out[22]:
tensor([[-0.3675, -0.5714, -1.4877, -0.6484, -2.0176],
        [ 0.7957,  2.4677,  1.3163, -0.6664,  2.9213]])

In [23]: x == tmp
Out[23]:
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])

In [24]: tmp
Out[24]:
tensor([[ 0.0937, -0.0519, -1.5766, -0.7709, -2.5773],
        [ 1.1673,  1.9548,  0.9662, -0.2257,  1.3812]])
```

**Review by XuesongYang — APPROVED** [review]

**Pull request merged**
