### PR TITLE
Add delay for speech codes prediction

### PR DESCRIPTION
**Pull request by kevinhu-nv**
# What does this PR do ?

Add delay to speech codes prediction.

### CODE REVIEW

**Comment by kevinhu-nv** [comment]
@zhehuaichen

**Review by zhehuaichen — APPROVED** [review]
Thank you so much! Can u attach a working recipe based on the same baseline as mine before merging
/lustre/fs12/portfolios/llmservice/users/zhehuaic/works/mod_speech_llm/scripts/s2s_salm_1ab_d1r_12fps_duplex4_data_scalec_mistral.sh

**Comment by zhehuaichen** [comment]
great. click the merge button when you verified that your recipe can train

**Comment by kevinhu-nv** [comment]
> great. click the merge button when you verify that your recipe can train

Already training :)

**Pull request merged**
