### PR TITLE
Fix for PyTorch 1.3

### PR DESCRIPTION
**Pull request by blisc**

### CODE REVIEW

**Comment by blisc** [comment]
It would be nice if someone could test this on pytorch 1.2

**Comment by redoctopus** [comment]
Works on my end with pytorch 1.2.

**Comment by okuchaiev** [comment]
the CI also passes and looks good to me. @blisc and @redoctopus , the real question is whether it should go into 0.8.1 or not? What do you think?

**Comment by redoctopus** [comment]
Seems to me that the sooner we have a fix for 1.3 the better, so I'd say yes. Is there a reason to keep it out currently?

**Comment by blisc** [comment]
I vote for merge, but keeping the pytorch 1.12 requirement for 0.8.1

**Pull request merged**
