### PR TITLE
Package setup refactoring

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
Important Package Refactoring of the collection additional repositories

## Project Update:
- Added `nemo/package_info.py` contains all the core information of the package, including version
- Added Changelog.md, please start using it ;) 

## To install:
- `pip install nemo_toolkit`  # Core Only
- `pip install nemo_toolkit[nlp]`  # Core + NLP
- `pip install nemo_toolkit[nlp,asr]`  # Core + NLP + ASR
- `pip install nemo_toolkit[all]`  # Absolutely everything

## To be noted:
When using `pip install -e`, you have to use quotes for dev purposes: `pip install -e ".[nlp]"`

### CODE REVIEW

**Comment by okuchaiev** [comment]
could you please sign your commits https://github.com/NVIDIA/NeMo/pull/289/checks?check_run_id=406125737

**Comment by DEKHTIARJonathan** [comment]
OIC yeah I need a GPG key ...

**Comment by okuchaiev** [comment]
no, you don't need a GPG key.   To sign them when you are commiting do "git commit -s" this is different from "git commit -S". DCO's bot output tells you how to sign commited commits.

**Comment by blisc** [comment]
Can you move README.md back into nemo/ since we already have the repo README as part of README.rst

**Comment by blisc** [comment]
What is requirements/requirements_test.txt?

**Comment by blisc** [comment]
Q: nemo_tts requires nemo_asr. Inside requirements_tts.txt, there is a line that says nemo_asr, I am assuming that this no longer works, how do we work around this?

**Comment by DEKHTIARJonathan** [comment]
> Q: nemo_tts requires nemo_asr. Inside requirements_tts.txt, there is a line that says nemo_asr, I am assuming that this no longer works, how do we work around this?

I'll modified this, thanks I did't see :)

**Pull request merged**
