### PR TITLE
adding MoE parameters to BERT model

### PR DESCRIPTION
**Pull request by clumsy**
# What does this PR do ?

Adding MoE parameter passing for BERT model.

**Collection**: NLP/Language Models/BERT

# Changelog 
- `bert_model.py` adding MoE parameters, passing them to `language_model`
- `megatron_bert_model.py` adding and passing MoE parameters
- `language_model.py` adding and passing MoE parameters

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by clumsy** [comment]
This PR follows the existing code in how parameters are passed specifying the default values multiple times in various places.

I wonder if this is being looked at or a different approach is being considered. E.g. using `dict` expansion (`**{}`) - this way the defaults could be set once.

**Comment by wdykas** [comment]
@shanmugamr1992 does this conflict with how we are going to be adding MoE to megatron core.

**Comment by shanmugamr1992** [comment]
@wdykas  I am not sure how MOE is excatly going to be added. @ericharper  Could you comment ?

**Comment by clumsy** [comment]
Now that MoE code has been update it appears the PR has no conflicts for the existing parameters I pass here. New parameters can be added separately. @shanmugamr1992 @wdykas

**Pull request closed without merging**
