### PR TITLE
fix device setting to allow using accelerator cpu

### PR DESCRIPTION
**Pull request by orena1**
# What does this PR do ?

It is currently impossible to run wav2vec with `trainer.accelerator=cpu` if the machine has a gpu. 
The padding_mask is already on the device set in `trainer.accelerator` but if the machine has a GPU the DEVICE variable will contain cuda and this error message will be received:

```
File /mnt/NVM/oren/anaconda3_10/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/modules/wav2vec_modules.py:348, in Wav2VecTransformerEncoder.create_padding_mask(self, length)
    345 padding_mask = torch.arange(max_len, device=DEVICE)
    347 # Switch to binary for transformer, 1 for valid tokens, 0 for padding
--> 348 padding_mask = (padding_mask.expand(len(length), max_len) < length.unsqueeze(1)).type(torch.uint8)
    350 return padding_mask

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```
  
**PR Type**:
- [x] Bugfix

# Additional Information
* Related to # (issue)
* 
@titu1994, @redoctopus, @jbalam-nv, or @okuchaiev

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
Makes sense, thanks for the fix ! @tbartley94 for final review

**Comment by titu1994** [comment]
jenkins

**Comment by orena1** [comment]
Thanks @titu1994 , see also here:
https://github.com/NVIDIA/NeMo/issues/8085

**Comment by titu1994** [comment]
jenkins

**Comment by tbartley94** [comment]
@titu1994 i know you pushed but just for record I'm not seeing any issues so review is approved

**Comment by titu1994** [comment]
Oh thanks for the update, I think I misremembered as this having your approval on slack somehow, turns out it was a different topic different pr. Sorry about that.

**Comment by orena1** [comment]
do you @titu1994  or @tbartley94 have any idea about this one:
https://github.com/NVIDIA/NeMo/issues/8085

**Comment by tbartley94** [comment]
Hmm, lemme take a look. I'd wager it's some tech debt between PTL versions. (fervor for wav2vec dipped before PTL 2.0 was released, so the code is likely working off a dated namespace.)

**Pull request merged**
