### PR TITLE
[WIP] Multi node support

### PR DESCRIPTION
**Pull request by khcs**
Minimal change for multi-node training support - checkpoint-saving fix.

### CODE REVIEW

**Comment by okuchaiev** [comment]
this fix seems to have changed my error, but I still encounter it :(
Getting something like this after I try to load a checkpoint from training on 32 nodes

Traceback (most recent call last):
  File "eval.py", line 104, in <module>
    main()
  File "eval.py", line 93, in main
    cache=True
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/core/neural_factory.py", line 599, in infer
    offload_to_cpu=offload_to_cpu)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/backends/pytorch/actions.py", line 1370, in infer
    mod.restore_from(checkpoint, self._local_rank)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/backends/pytorch/nm.py", line 106, in restore_from
    self.load_state_dict(t.load(path, map_location=load_device))
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 512 got 65536

**Comment by khcs** [comment]
@okuchaiev , can you point me to the code that I can test multi-node training on?
The BERT pre-training that was working earlier needs more change to be merged into the current code-base.

**Comment by okuchaiev** [comment]
tested with QuartzNet (a Jasper variant) using this commit 4baadac4c651243040e2e01d9b4be952c19b466a  (e.g. top of this PR)

**Comment by yzhang123** [comment]
i was able to load multinode checkpoint for bert using this pull request https://github.com/NVIDIA/NeMo/pull/136

**Comment by blisc** [comment]
I don't understand why this is necessary. save_to is only called in three class methods, and all three class methods have this check:
`if self.local_rank is None or self.local_rank == 0:`
While it might be a good idea to move this inside of save_to() as opposed to doing this check and then calling save_to(). I don't see why we need all this `def is_main_process():` helper function

**Comment by blisc** [comment]
Ok I understand the issue now. local_rank != torch.distributed.get_rank()

**Comment by blisc** [comment]
@khcs If #139 fixes this issue, should we close this PR?

**Comment by okuchaiev** [comment]
looks like we did some other PRs partly based on this. I think we can close this one. @khcs please re-open if you disagree (but rebase on current master then)

**Pull request closed without merging**
