### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by ekmb**

### CODE REVIEW

**Review by okuchaiev — CHANGES_REQUESTED** [review]
can you please replace all references to 1.0.0b2 with 1.0.0b3 in README.md ?

**Comment by ekmb** [comment]
> can you please replace all references to 1.0.0b2 with 1.0.0b3 in README.md ?

@okuchaiev 1.0.0b3 won't work, the notebooks were not updated from `1.0.0b2` to `1.0.0b3` when 1.0.0b3 was released. for example, this [one with `/blob/v1.0.0b3/`](https://colab.research.google.com/github/NVIDIA/NeMo/blob/v1.0.0b3/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb) will install `BRANCH=1.0.0b2`

**Comment by okuchaiev** [comment]
can you please put paths like https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb ?

and we'll update notebooks in r1.0.0b3 to install from r1.0.0b3

**Comment by ekmb** [comment]
> can you please put paths like https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb ?
> 
> and we'll update notebooks in r1.0.0b3 to install from r1.0.0b3

But what about bug fixes, like this one https://github.com/NVIDIA/NeMo/pull/1558 ?

**Review by okuchaiev — APPROVED** [review]

**Pull request merged**
