### PR TITLE
Load ub_cfg from hydra config

### PR DESCRIPTION
**Pull request by jbaczek**
# What does this PR do ?

Remove the need to load the yaml module inside GPT model and use hydra config instead.

**Collection**: nlp

# Changelog 
- For ub_tp_comm_overlap_cfg config field you no longer provide a path to the config but the whole config instead.

# Usage
If you add to your main config:
```yaml
defaults:
  [...]
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg:
```
then you can load the config from a known location like this:
` ++  tp_overlap@model.ub_tp_comm_overlap_cfg=<tp_config}`

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by jbaczek** [comment]
@ericharper can you review this PR?

**Comment by erhoo82** [comment]
LGTM Please assign me and @ericharper as the reviewers.

**Review by erhoo82 — APPROVED** [review]
LGTM

**Comment by erhoo82** [comment]
@ericharper Can you review this PR?

**Comment by erhoo82** [comment]
@jbaczek 
I tested and I see it didn't work. I checked that correct yaml file is passed without `yaml`. I printed but not a dict was passed but just text.

**Comment by jbaczek** [comment]
@erhoo82 can you elaborate? What command did you type? What is your conf directory structure?

**Review by titu1994 — APPROVED** [review]
Thanks for the guard !

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
