### PR TITLE
read system token from data in gpt_sft_chat_dataset

### PR DESCRIPTION
**Pull request by shengyangs**
# What does this PR do ?

The original implementation of the prompt template in `gpt_sft_chat_dataset.py` uses a fix system token `System`. 

This PR enables to read the system token from the dataset so that it is configurable. This enables us to include more prompt templates such as the llama3 prompt template.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [x ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

@yidong72 

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by yidong72 — APPROVED** [review]
LGTM

**Comment by yidong72** [comment]
> @yidong72 Shall we contact someone to conduct the CI?

I think we need to add "RUN CICD" label to it. let's see if it kicks off the tests

**Comment by shengyangs** [comment]
@yidong72  can you review it again? I updated the `get_prompt_template_example` function.

**Comment by shengyangs** [comment]
@yidong72 @ko3n1g Please take a look at it. Thanks!

**Pull request closed without merging**
