### PR TITLE
[BugFix] Adding task variable for torchmetrics Accuracy

### PR DESCRIPTION
**Pull request by tango4j**
Signed-off-by: Taejin Park <tango4j@gmail.com>

# What does this PR do ?

In the latest `torchmetrics==0.11.0`, Accuracy class' `__init__()` requires `task` variable to be specified.
Adding task variable for torchmetrics Accuracy

**Collection**: [Note which collection this PR will affect]
ASR

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
This is bugfix for label_models.py

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anybody in ASR

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ericharper** [comment]
Can you also remove the upper bound on Torchmetrics in our requirements ?

**Comment by tango4j** [comment]
> 

Removed upperbound.

**Comment by ericharper** [comment]
Also, do we need to increase the lower bound with this change? Or is it backwards compatible?

**Comment by tango4j** [comment]
> Also, do we need to increase the lower bound with this change? Or is it backwards compatible?

For the label_models.py, it 

> Reference
label_models.py seems to be compatible with 0.7.0 and 0.8.0. 
`pytorch-lightning 1.8.3 requires torchmetrics>=0.7.0, but you have torchmetrics 0.4.1 which is incompatible`
According to this message, I think it is better to be `torchmetrics>=0.7.0`? How do you think on this?

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Pull request closed without merging**
