### PR TITLE
adding special_tokens from tokenizer config for transformer-lm model

### PR DESCRIPTION
**Pull request by clumsy**
# What does this PR do ?

`special_tokens` are currently ignored when constructing a tokenizer for `transformer_lm_model` using the following example: https://github.com/NVIDIA/NeMo/blob/5cb76a53f21d7470773a80d62fd513defa24ddbf/examples/nlp/language_modeling/conf/bert_pretraining_from_text_config.yaml#L51

**Collection**: NLP/language-modeling

# Changelog 
- transformer_lm_model: use `special_tokens` from config when creating the tokenizer, making it backward-compatible with previous behavior (when `special_tokens` are not provided we proceed with `None`).

# Usage
* https://github.com/NVIDIA/NeMo/blob/5cb76a53f21d7470773a80d62fd513defa24ddbf/examples/nlp/language_modeling/conf/bert_pretraining_from_text_config.yaml#L51

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
 - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by shanmugamr1992 — APPROVED** [review]

**Comment by wdykas** [comment]
@ericharper for visibility when you get the chance fix for using special tokens

**Comment by clumsy** [comment]
@ericharper , @wdykas is there anything I can do from my end to unblock this PR?

**Comment by clumsy** [comment]
Please let me know if there's anything I can do to get this PR approved, @wdykas @ericharper. Thanks!

**Comment by aklife97** [comment]
this PR should be good to go but we need to ensure we do not do this special token passing for sentencepiece. We know it causes different tokenization as compared to a standard pre-trained sentencepiece model and can cause hidden issues

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
@aklife97 are you recommending that we add a check in this PR?

**Comment by aklife97** [comment]
I think it should be good to merge, we need to think of a more general solution for this...

**Pull request merged**
