### PR TITLE
Offline asr notebook bug fix

### PR DESCRIPTION
**Pull request by fayejf**
- [x] Remove .cpu().numpy()
- [x] Add -y when apt-get install swig
- [x] Check and install ipywidgets for tdqm/notebook

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
Looks great, merge when ready

**Comment by nchaika** [comment]
@fayejf  Hi! I have just tried to run the script and it failed at e = np.exp(logits - np.max(logits)) for the wrong argument type.
Why did you remove converting torch.tensor into numpy array? 
detach().cpu().numpy() is still needed for the method to run properly.

**Comment by titu1994** [comment]
With the main branch, transcribe() method will return numpy arrays of logits instead of torch tensors to preserve gpu memory after transcription has occurred. 

Could you paste the error trace here ?

**Comment by nchaika** [comment]
I added detach().cpu().numpy() to logits and it ran without errors.
Would you like me to rerun it without converting and show the error?

**Comment by fayejf** [comment]
Yes, please. Which version/branch are you using?

**Comment by nchaika** [comment]
I am using current main, not sure which is the latest version. I modified the script a bit (cut the analysis with librosa and plots from it, as the server where I am running the script does not support it).
Without correcting logits, trace is as follows:

```
Transcribing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.30it/s]
Transcript: "i cannot follow you she said"
Transcribing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.81it/s]
Traceback (most recent call last):
  File "transcribe_audio_with_timestamps.py", line 110, in <module>
    probs = softmax(logits)
  File "transcribe_audio_with_timestamps.py", line 98, in softmax
    e = np.exp(logits - np.max(logits))
  File "<__array_function__ internals>", line 6, in amax
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 85, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: max() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * ()
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
 * (Tensor other)
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
```

**Comment by fayejf** [comment]
This should be works with main branch as well.

Could you run

```
cd NeMo
./reinstall.sh
```
and try again?

**Comment by nchaika** [comment]
Ok, I fetched the main branch, recompiled and it worked. So I guess I didn't have some new changes, not sure when they appeared. Thanks for pointing it out!

**Pull request merged**
