### PR TITLE
Add knobs for swiglu and rope fusion

### PR DESCRIPTION
**Pull request by lhb8125**
# What does this PR do ?

Add knob for rope fusion
Add knob for swiglu fusion
Change knob for bias_gelu fusion

The PR is related to the PR of MLM: https://gitlab-master.nvidia.com/ADLR/megatron-lm/-/merge_requests/984

**Collection**: [NLP]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* set `model.apply_rope_fusion: true` to enable rope fusion
* set `model.bias_activation_fusion: true` to enable bias+activation fusion, which works for both gelu and swiglu type.

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
Add @ericharper @erhoo82 for review.
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by erhoo82** [comment]
jenkins

**Review by cuichenx — APPROVED** [review]
LGTM!

**Comment by cuichenx** [comment]
Actually, should we default `apply_rope_fusion` to True or False?
Before this PR it would be been "False". Are there risks to changing the default behavior to "True" now?

**Comment by lhb8125** [comment]
> Actually, should we default `apply_rope_fusion` to True or False? Before this PR it would be been "False". Are there risks to changing the default behavior to "True" now?

I think we should keep it as true at most cases since rope is a separated operator and well fused in apex. MCore will check if the fused implementation is included in apex, or the config will be set to false.

**Comment by cuichenx** [comment]
> > Actually, should we default `apply_rope_fusion` to True or False? Before this PR it would be been "False". Are there risks to changing the default behavior to "True" now?
> 
> I think we should keep it as true at most cases since rope is a separated operator and well fused in apex. MCore will check if the fused implementation is included in apex, or the config will be set to false.

Cool, thanks!

**Comment by ericharper** [comment]
jenkins

**Comment by lhb8125** [comment]
The changes have been enabled in another cleaner PR: https://github.com/NVIDIA/NeMo/pull/8184.
Close it now.

**Pull request closed without merging**
