### PR TITLE
Update `ema.py` for full Lightning 2.0 and 2.1 support

### PR DESCRIPTION
**Pull request by amorehead**
# What does this PR do ?

Updates `ema.py` for full Lightning 2.0 and 2.1 support, and also adds full docstrings for the EMA `Callback` and its components.

# Changelog 
- Update imports for the `EMA` `Callback`
- Add docstrings to the `EMA` `Callback`

# Usage
* Being able to use the `EMA` `Callback` in Lightning 2.0 as well as Lightning 2.1 models.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

### CODE REVIEW

**Comment by SeanNaren** [comment]
Thanks for this PR @amorehead :)

The changes I noticed are failing (and the CI), this is due to me installing `pytorch-lightning` as apposed to `lightning`. I assume `lightning` contains other pieces other than just the Trainer centric items, but I may be wrong. When I install `pytorch-lightning`, the `lightning` import isn't available, but `pytorch-lightning` is. This is how its set up on the requirements too

So I think the EMA Code should work if you install the latest `pytorch-lightning` as apposed to `lightning`? The docs are great though, so if what I'm saying is true we should get them in atleast :)

**Comment by amorehead** [comment]
Hey, @SeanNaren. No problem. The reason I tried switching to `lightning` imports instead of `pytorch-lightning` imports is that, starting in PyTorch Lightning (PL) 2.1, the original `pytorch-lightning` imports are being phased out in favor of the generic `lightning` imports (e.g., `lightning.pytorch.xyz` vs. `pytorch_lightning.xyz`). Specifically, in PL 2.1, an error is raised when users try to import the following modules using `pytorch_lightning`, effectively saying that some of these modules can no longer be used with the `lightning` packages' modules.

Starting in PL 2.0+, the `pytorch_lightning` imports can be interchanged here for the `lightning` imports, with some of the modules listed below changing package locations. In particular, `lightning` version 2.0 and up comes bundled with the `pytorch_lightning` package for backwards compatibility with codebases written using the original `pytorch_lightning` package. If the NeMo team is not comfortable with adding the `lightning` package explicitly to the `requirements-lightning.txt` file at this time, I can revert the imports back to `pytorch_lightning`. Just let me know what you all would prefer. If and when the team, would like to upgrade to Lightning 2.1, we can simply reference this PR to add these changes back.

Original imports:
```bash
import pytorch_lightning as pl
from pytorch_lightning import Callback
from pytorch_lightning.utilities.exceptions import MisconfigurationException
from pytorch_lightning.utilities.rank_zero import rank_zero_info
```

**Comment by SeanNaren** [comment]
Thanks @amorehead, I didn't have this visibility so that's great to know.

@athitten it seems that for long term future proofing we should swap our requirements from `pytorch-lightning` to `lightning`. Do you agree here? Curious if there is any pitfalls from this.

**Comment by athitten** [comment]
> Thanks @amorehead, I didn't have this visibility so that's great to know.
> 
> @athitten it seems that for long term future proofing we should swap our requirements from `pytorch-lightning` to `lightning`. Do you agree here? Curious if there is any pitfalls from this.

@SeanNaren @amorehead I would stick with importing `pytorch_lightning` for now to keep it consistent with the code base. We are currently working on upgrading NeMo to PL 2.1 and with that we can change `pytorch_lightning` to `lightning` if we can't use `pytorch_lightning` anymore.

**Comment by amorehead** [comment]
@athitten, in which case, I've reverted to using `pytorch_lightning` imports for this PR. It should now only include docstring and minor formatting changes. Let me know if this all looks good to you.

**Comment by amorehead** [comment]
@SeanNaren, I believe this PR should be good to go. LMK if you have any additional comments.

**Pull request closed without merging**
