### PR TITLE
Token count and sequence length logging for MegatronGPTSFTModel

### PR DESCRIPTION
**Pull request by vysarge**
# What does this PR do ?

Adds an option to enable progress bar logging for sequence length (including padding tokens) and real token count for each train step with MegatronGPTSFTModel to enable accurate calculation of tokens/sec and related metrics.

**Collection**: nlp/language_modeling

# Changelog 
- Alters GPTSFTDataset and GPTSFTPackedDataset to pass out a list of token counts as part of the batch
- Alters MegatronGPTSFTModel to expect, average, and log that list of token counts at the beginning of the step if enabled via config

# Usage

```
python megatron_gpt_peft_tuning.py \
    ... \
    ++model.log_token_counts=true
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

### CODE REVIEW

**Comment by vysarge** [comment]
@cuichenx / @ericharper can you review?

**Review by erhoo82 — APPROVED** [review]
LGTM

**Comment by cuichenx** [comment]
jenkins

**Review by cuichenx — APPROVED** [review]
+1 LGTM Thanks

**Comment by erhoo82** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
