### PR TITLE
removed unused imports for all domains.

### PR DESCRIPTION
**Pull request by XuesongYang**
Signed-off-by: Xuesong Yang <1646669+XuesongYang@users.noreply.github.com>

# What does this PR do ?
LGTM.com detected 100 ish unused imports. Clean up to remove those warnings.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by SeanNaren — APPROVED** [review]
would be nice if we have some `pre-commit` CI that can detect unused imports when merging a PR. not sure if you considered this @soumye, you can see Lightning's here: https://github.com/Lightning-AI/lightning/blob/master/.pre-commit-config.yaml

**Comment by XuesongYang** [comment]
> would be nice if we have some `pre-commit` CI that can detect unused imports when merging a PR. not sure if you considered this @soumye, you can see Lightning's here: https://github.com/Lightning-AI/lightning/blob/master/.pre-commit-config.yaml

Thanks, @SeanNaren, yes, `pre-commit-hooks` is great to have. But we may need an automatic deletion for those unused imports beyond detecting them. There was a feature request for `isort`: https://github.com/PyCQA/isort/issues/1105, but it seems the final decision goes with the trick "run autoflake; then isort". @ericharper @titu1994 any advice on this?

**Review by titu1994 — APPROVED** [review]
This is amazing work, thank you !

**Comment by titu1994** [comment]
Regarding the precommit. Im a bit worried about cases where we deliberately want unused import (say inside init files for proxy import paths) - asr has some such cases. 

As long as we can do one of  -
1) set up sections or files to ignore auto removal of unused imports
2) have some manual override of where to not remove imports 

It's fine to use pre commit hooks.

**Comment by XuesongYang** [comment]
> 



> 



> Regarding the precommit. Im a bit worried about cases where we deliberately want unused import (say inside init files for proxy import paths) - asr has some such cases.
> 
> As long as we can do one of -
> 
> 1. set up sections or files to ignore auto removal of unused imports
> 2. have some manual override of where to not remove imports
> 
> It's fine to use pre commit hooks.

Thanks for the comments. Yes, we need to be careful when removing ones in `__init__.py`. `autoflake` (https://github.com/PyCQA/autoflake) provides an option `--ignore-init-module-imports`, i.e. exclude `__init__.py` when removing unused imports, to safeguard this scenario.

**Pull request merged**
