### PR TITLE
fix the versioning name.

### PR DESCRIPTION
**Pull request by VahidooX**
Fix the versioning name to avoid creating the extra folder name "None"  when training is supposed to continue.

### CODE REVIEW

**Review by titu1994 — COMMENTED** [review]
Doesn't this just dump the files into the project dir? @blisc any thoughts if this is correct ?

**Comment by VahidooX** [comment]
> 
> 
> Doesn't this just dump the files into the project dir? @blisc any thoughts if this is correct ?

Actually I made this from "" to None last time to hope it fixes the w&b but it made the issue that now we have a folder name "None" and then there is another folder under that named "checkpoints" where checkpoints are getting stored under. They would not get dumped into the project folder but under a folder named checkpoints.

**Comment by blisc** [comment]
Hmm I see, we need it to be None for future code but doing `Path(str(None))' returns "None" when we need it to be empty string

**Comment by titu1994** [comment]
How about explicitly checking for "None" and then replacing it with ""

**Comment by VahidooX** [comment]
> 
> 
> How about explicitly checking for "None" and then replacing it with ""

Did this this way. Now the version property in the config would be set to None instead of "".

**Comment by titu1994** [comment]
This overall looks like a good solution, @blisc to confirm the approach is correct and merge if its fine.

**Review by blisc — APPROVED** [review]

**Pull request merged**
