### PR TITLE
Draft:add fp8 weight caching to mcore_gpt

### PR DESCRIPTION
**Pull request by JimmyZhang12**
# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by JimmyZhang12** [comment]
@erhoo82 can you please review?

**Comment by erhoo82** [comment]
Can you add the case handling the validation step as well? At validation, we need to cache the fp8 w/t at the first micro-batch in the first global batch, and no need to cache in the following global batches. I think you can use `model.training` to tell if the current micro-batch belongs to the training or validation routine.

This is the reference. 
https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/modules/common/megatron/transformer.py#L1543-L1544

**Comment by JimmyZhang12** [comment]
I tested validation and it seems ok; the global batch size is the same between validation and training, so the is_first_microbatch logic is unaffected, and validation and training both share `get_forward_output_and_loss_func`
The case where the global batch size is changed should be handled by this [code](https://github.com/NVIDIA/NeMo/blob/99fa120c637bafd7ec364ff2159661ec0784a4e0/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py#L890):

**Comment by erhoo82** [comment]
In validation, we only need to cache the fp8 w/t at `the first global-batch` + `the first micro-batch`. Did you check if fp8 w/t is not cached in the other first micro-batch in the later global-batch?

**Comment by JimmyZhang12** [comment]
Good point thanks, I added a fix for validation

**Pull request closed without merging**
