### PR TITLE
MCore dataset compatibility for tokenizers

### PR DESCRIPTION
**Pull request by vysarge**
# What does this PR do ?

Adds properties required by megatron-core to NeMo tokenizers via the base TokenizerSpec class (see #8283).

**Collection**: common (tokenizers)

# Changelog 
- Adds a `unique_identifiers` OrderedDict which is needed when using alongside megatron-core datasets (following [megatron_tokenizer.py](https://github.com/NVIDIA/Megatron-LM/blob/0052bf0de70b266d8648e2655da16f7eb2c9ca56/megatron/core/datasets/megatron_tokenizer.py))
- Adds several property-decorated methods as aliases for equivalent properties already present in tokenizers that inherit from TokenizerSpec
- Removes now-redundant individual fix from AutoTokenizer

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by vysarge** [comment]
@ericharper / @dimapihtar can you review this fix?  Thanks!

**Review by pablo-garay — APPROVED** [review]

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Comment by pablo-garay** [comment]
jenkins

**Pull request merged**
