### PR TITLE
Option to disable mp in VAD via num_workers=1

### PR DESCRIPTION
**Pull request by gkucsko**
In certain environments python multiprocessing can deadlock. This adds a convenient version to disable by setting num_workers to 1.

### CODE REVIEW

**Comment by gkucsko** [comment]
@tango4j mind having a quick look? thanks!

**Comment by tango4j** [comment]
> @tango4j mind having a quick look? thanks!

Could you change the line to add `if config['num_workers'] is not None and num_worker > 1:` to prevent error case to prevent error from `config['num_workers']=None`?

**Comment by gkucsko** [comment]
done, thanks. anything else?

**Comment by tango4j** [comment]
> 

It is working fine with the change, but not passing CI.  

> done, thanks. anything else?

Can you add line 693 if num_workers is not None and num_workers > 1: too ?

**Comment by gkucsko** [comment]
sure thing!

**Review by fayejf — APPROVED** [review]
LGTM! Thank you so much!

**Comment by fayejf** [comment]
Yes seems like python multiprocessing can deadlock in certain environments, and this is an unsolved issue in python now. Thanks for the fix! @gkucsko 

For anyone is interested in using multiprocessing in VAD to accelerate the process. I'm with Python 3.7.11 and it works perfectly fine on my end

**Pull request merged**
