### PR TITLE
Clean up ASR augmentor config docs

### PR DESCRIPTION
**Pull request by redoctopus**
Removed redundant parameter table
Signed-off-by: Jocelyn Huang <jocelynh@nvidia.com>

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]

**Comment by blisc** [comment]
It's up to you if you want to merge it or not. My concern is that we are lacking good docstrings and are trying to make up for it by adding it in the documentation

**Comment by titu1994** [comment]
LGTM merge when ready

**Comment by titu1994** [comment]
Ideally the API documentation for this module should incorporate the above information. So just adding it to the docstring will add it to the API

**Comment by redoctopus** [comment]
> It's up to you if you want to merge it or not. My concern is that we are lacking good docstrings and are trying to make up for it by adding it in the documentation

I think this one is fine to remove from the docs; everything here is already covered in the `SpectrogramAugmentation` docstring so we don't lose anything by deleting it from this page.
(https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/api.html#nemo.collections.asr.modules.SpectrogramAugmentation)

**Pull request merged**
