### PR TITLE
VAD inference tutorial

### PR DESCRIPTION
**Pull request by fayejf**
@okuchaiev I've tried to test the online part on my laptop but seems like there is something wrong with my microphone. Could you please help me test it on your computer? Thanks in advance

And for name convention, I just follow the asr and call it asr_model and FrameASR instead of vad_model and FrameVAD. I think it's probably fine cause vad is under asr folder, but we can change it to vad-ish if it's better.

### CODE REVIEW

**Review by okuchaiev — CHANGES_REQUESTED** [review]
I get this error when running locally on machine with GPU:

```
~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/repos/NeMo/nemo/collections/asr/parts/jasper.py in forward(self, input_)
    537             # if (i % 4) == 0 and self.conv_mask:
    538             if isinstance(l, MaskedConv1d):
--> 539                 out, lens = l(out, lens)
    540             else:
    541                 out = l(out)

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/repos/NeMo/nemo/collections/asr/parts/jasper.py in forward(self, x, lens)
    172             x = x.view(-1, self.heads, sh[-1])
    173 
--> 174         out = self.conv(x)
    175 
    176         if self.heads != -1:

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py in forward(self, input)
    255                             _single(0), self.dilation, self.groups)
    256         return F.conv1d(input, self.weight, self.bias, self.stride,
--> 257                         self.padding, self.dilation, self.groups)
    258 
    259 

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
```


I get this error when running on Colab:
```
====== STEP is 0.01s, WINDOW_SIZE is 0.31s ====== 

---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

<ipython-input-19-9d5a41d46b53> in <module>()
      2 for STEP, WINDOW_SIZE in zip(STEP_LIST, WINDOW_SIZE_LIST):
      3     print(f'====== STEP is {STEP}s, WINDOW_SIZE is {WINDOW_SIZE}s ====== ')
----> 4     preds, proba_b, proba_s = offline_inference(wave_file, STEP, WINDOW_SIZE)
      5     results.append([STEP, WINDOW_SIZE, preds, proba_b, proba_s])

2 frames

/usr/local/lib/python3.6/dist-packages/pyaudio.py in __init__(self, PA_manager, rate, channels, format, input, output, input_device_index, output_device_index, frames_per_buffer, start, input_host_api_specific_stream_info, output_host_api_specific_stream_info, stream_callback)
    439 
    440         # calling pa.open returns a stream object
--> 441         self._stream = pa.open(**arguments)
    442 
    443         self._input_latency = self._stream.inputLatency

OSError: [Errno -9996] Invalid output device (no default output device)
```

Also, can you please make few minor changes:
(1) After user downloads "VAD_demo_wav" - can you add playable widget (IPython.display.Audio(wav_file))

Should we make this local-only because it needs access to microphone? Or Colab can read from mic?

**Comment by fayejf** [comment]
Ah seems like the model and data are not in the same place. Will fix it

The Colab error is expected. Yes output/input issue happens to asr inference on colab too. Well colab can read / record from mic but I haven't figured out how to make it work together with pyaudio. And also this will include a few of code not related to our inference tutorial). To keep it safe, maybe ask them to run locally or set up microphone for colab for now?

Do our user heavily depend on colab?

**Comment by okuchaiev** [comment]
let's make this local only. we'll worry about colab later if we decide that it is necessary

**Comment by fayejf** [comment]
@okuchaiev  Hi Oleksii I've fixed the "wrong place for data and model" issue in VAD and ASR notebook (caused by map_location in from_pretrained I guess). And other comments are handled too. Could you please have a look and try again? Thanks!

**Review by okuchaiev — APPROVED** [review]
works for me now. thanks!

**Comment by fayejf** [comment]
@okuchaiev Thanks a lot!!

**Pull request merged**
