### PR TITLE
Fix semi_sorted paper link

### PR DESCRIPTION
**Pull request by orena1**
# What does this PR do ?

Fix semi_sorted paper link

### CODE REVIEW

**Comment by orena1** [comment]
@titu1994 why this was closed?

**Comment by orena1** [comment]
@nithinraok why is this closed? shouldn't we fix the paper link ?

**Comment by nithinraok** [comment]
Please add changes from https://github.com/NVIDIA/NeMo/pull/10711 to here and rebase with main.

**Comment by orena1** [comment]
@nithinraok is this ok now?

**Review by nithinraok — APPROVED** [review]

**Pull request merged**
