### PR TITLE
Sanity checks for unfinished checkpoints removal

### PR DESCRIPTION
**Pull request by jbieniusiewi**
# What does this PR do ?

The following scenario was recently observed:
- Last checkpoint writing was interrupted due to an irrelevant issue
- Hence last checkpoint was marked as "unfinished" (and there was no other last checkpoint)
- Hence the following training silently skipped the last checkpoint and started from scratch
- As a result, training was not making expected progress despite many training runs

This PR adds some sanity checks to ensure that when the last/end checkpoint is unfinished, it wont get silently skipped and deleted. Instead, user is supposed to remove them manually. 

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by maanug-nv — DISMISSED** [review]
Thanks @jbieniusiewi . Very simple, and should consistently avoid that training restart we saw, even with auto relaunch.

**Comment by maanug-nv** [comment]
@jbieniusiewi could you also add the same check for 2.0. The unfinished filtering is [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/lightning/resume.py#L112-L113) in 2.0.

**Comment by jbieniusiewi** [comment]
Thank you for the review @maanug-nv. 
I've added check for NeMo 2.0. One more approval is needed to merge it, so I re-requested a review.

**Comment by maanug-nv** [comment]
@ashors1 Do we have/plan to have tests for AutoResume?

**Comment by jbieniusiewi** [comment]
@maanug-nv Sure, I've added tests to ``tests/lightning/test_nemo_logger.py``.

**Review by pzelasko — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
