### PR TITLE
tune specific params in the base model

### PR DESCRIPTION
**Pull request by arendu**
# What does this PR do ?

tune only a selected subset of the params of the base model.

**Collection**: [NLP]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ertkonuk** [comment]
I think it looks good.

**Comment by arendu** [comment]
jenkins

**Comment by arendu** [comment]
jenkins

**Review by cuichenx — CHANGES_REQUESTED** [review]
Could you rename `tunable_param_*` to `tunable_base_model_param_*` and/or add a comment to specify it's for selective tuning? just because adapter weights are also tunable so it might be confusing

**Comment by arendu** [comment]
jenkins

**Review by cuichenx — DISMISSED** [review]
Looks great, thanks!

**Comment by cuichenx** [comment]
jenkins

**Comment by arendu** [comment]
jenkins

**Comment by cuichenx** [comment]
jenkins

**Pull request merged**
