### PR TITLE
fix to avoid 'DATA_DIR not found'

### PR DESCRIPTION
**Pull request by khcs**
Signed-off-by: Hoo Chang Shin <hshin@nvidia.com>

### CODE REVIEW

**Review by ekmb — COMMENTED** [review]
@khcs could you please remove the output?

**Comment by khcs** [comment]
Thanks @ekmb , just did :)

**Review by ekmb — APPROVED** [review]

**Review by ekmb — CHANGES_REQUESTED** [review]
@khcs please rebase to the rc1 branch

**Comment by okuchaiev** [comment]
yes please, this looks like bugfix for r1.0.0rc1

**Comment by khcs** [comment]
Thanks @ekmb and @okuchaiev - rebasing to r1.0.0rc1 resulted in many file changes, but notebook hasn't changed at all.

**Pull request closed without merging**
