### PR TITLE
Remove .nemo instead of renaming

### PR DESCRIPTION
**Pull request by mikolajblaz**
# What does this PR do ?

This is a fix to #9015 which resulted in creating too many .nemo files.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by titu1994** [comment]
Docstring needs to be updated but overall ok

**Review by titu1994 — APPROVED** [review]
Docstring needs update

**Review by titu1994 — DISMISSED** [review]
Thanks !

**Review by artbataev — COMMENTED** [review]
Please also add checks for the behavior in tests (`tests/core/test_exp_manager.py`) to avoid such a bug in future, as suggested in #9232
```python
def test_nemo_checkpoint_always_save_nemo(self, tmp_path):
    ...
    assert len(list((tmp_path / "test/checkpoints").glob("default*.nemo"))) == 1  # check number of `.nemo` checkpoints
```

**Comment by mikolajblaz** [comment]
@titu1994 CI on `main` branch is failing so I added a fix which is unrelated to this PR so that CI passes:
https://github.com/NVIDIA/NeMo/pull/9281/files#diff-efe139cc50f2253e4a5f2b5a268dff86f1094531de824da4067590243be7f928R25

**Comment by mikolajblaz** [comment]
There are some issues with the CI, @pablo-garay can you take a look?

@titu1994 I assume it needs to go to 2.0.0.rc as well?

**Review by pablo-garay — APPROVED** [review]

**Comment by titu1994** [comment]
Yup needs to be cherry picked into 2.0 as well

**Pull request merged**
