### PR TITLE
dllogger - log on rank 0 only

### PR DESCRIPTION
**Pull request by stas00**
# What does this PR do ?

As discussed in https://github.com/NVIDIA/NeMo/issues/7495 @titu1994 helped me to make Dllogger to log on rank0 as otherwise the metrics log happens 512 times per step on 512 gpus.

Fixes: https://github.com/NVIDIA/NeMo/issues/7495

**Collection**: [Note which collection this PR will affect]

# Changelog 
- make Dllogger to log on rank0 as otherwise the metrics log happens 512 times per step on 512 gpus.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [X] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to https://github.com/NVIDIA/NeMo/issues/7495

### CODE REVIEW

**Comment by titu1994** [comment]
This looks good ! Could you add a comment to the init docstring ?

**Review by titu1994 — APPROVED** [review]
Thanks !

**Comment by titu1994** [comment]
Let's merge as is for now, thanks for the PR !

**Comment by stas00** [comment]
After sleeping on this, are we sure this is a good solution? What if someone wants all ranks logged on Dllogger?

After all the users already define the value of `log_local_rank_0_only` so why not call `.log` conditionally on this value instead of hardcoding things to a way that would be hard to reverse down the road.

**Comment by titu1994** [comment]
Well the best case would be dllogger supports distributed logging. 
Barring that, your suggestion makes sense but it's not just one flag, its also the global rank 0 only. Also, how would you make it work with local rank 0 only - we have a function only to check if your global rank is 0, not to check local rank is 0. 

I would say, let the dllogger class constructor take a bool, rank_zero_only - and when creating the object in Exp Manager, we do rank_zero_only=local rank zero only OR global rank zero only. 

Next part is doing this bool check and only then checking if ptl rank zero check is true or not, then calling dllogger.log(). 

It's complicated but doable I guess

**Comment by titu1994** [comment]
Your new proposal with both flags is fine but put all that logic inside of the constructor of DLLogger class, not outside it inside exp Manager. Exp Manager will not specialize to any one logger, that's the individual loggers responsibility to manage itself.

**Comment by titu1994** [comment]
Well we can generalize later if needed. At the moment just dl logger needs this support

**Pull request merged**
