### PR TITLE
Rename Finetuning Scripts

### PR DESCRIPTION
**Pull request by cuichenx**
# What does this PR do ?

Rename certain unified SFT/PEFT scripts to remove reference to 'PEFT' in the script name, since it was confusing for people to run SFT with a 'peft' script
Rename `*_peft_tuning*` to `*_finetuning*` to include both SFT and PEFT in naming.
Rename `*_peft_eval*` to `*_generate*` to achieve the above and also make clear that the script is simply used to generate text (run inference), and not calculate any metrics.
Old scripts are kept until the next release, with a deprecation message added.

Also making deprecating messages more prominent, with a banner and a wait timer so the message does not get drowned in other nemo logging messages.

**Collection**: NLP

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation
- [x] UX Improvement

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by cuichenx** [comment]
jenkins

**Comment by cuichenx** [comment]
jenkins

**Comment by cuichenx** [comment]
jenkins

**Review by ericharper — DISMISSED** [review]
LGTM. Thanks!

**Comment by cuichenx** [comment]
jenkins

**Comment by cuichenx** [comment]
jenkins

**Comment by arendu** [comment]
LGTM!

**Review by arendu — APPROVED** [review]

**Pull request merged**
