### PR TITLE
[lhotse] Support for NeMo tarred manifests with offset field

### PR DESCRIPTION
**Pull request by pzelasko**
# What does this PR do ?

Support for NeMo tarred manifests with offset field in lhotse dataloading.

**Collection**: ASR

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by zhehuaichen — APPROVED** [review]
looks good to me . @KunalDhawan  or @tango4j  can either of you guys also take a look?
I will do a test with this PR

**Review by KunalDhawan — APPROVED** [review]
LGTM, thank you Piotr!

**Comment by vadimkantorov** [comment]
@pzelasko I checked, caching `TarInfo`s with a single linear scan lets then extract in O(1):
```python
import tarfile

def taropen_build(tar_path):
    tar = tarfile.open(tar_path)
    tarinfo_index = {tarinfo.name : (tarinfo, tarinfo.offset_data, tarinfo.size) for tarinfo in tar.getmembers()}
    # alternatively can just cache `offset_data` and `size`, and then seek/read directly from the tarfile
    return lambda member_path, mode: tar.extractfile(tarinfo_index[member_path][0]) if mode == 'rb' else None

if __name__ == '__main__':
    taropen = taropen_build('myfile.tar')
    print(taropen('mymember.txt', 'rb').read())
```

Supporting `.tar`s with wav/opus files inside would be very nice, as these small audio files can be in 10s or 100s of thousands which is always a pressure on the file system and adds time to unpacking

**Comment by pzelasko** [comment]
We already support tars with wav/opus. Linear scan is not feasible for URL data sources (cloud storage, AIStore).

**Pull request merged**
