### PR TITLE
Pre-generate cu_seqlens argmin and max_seqlen to remove host-to-device sync

### PR DESCRIPTION
**Pull request by erhoo82**
…e data copies

# What does this PR do ?

At SFT, pre-generate `cu_seqlens_argmin` and `max_seqlen` to skip CPU-side computation on the main process.
This removes host-to-device sync, which is performance-critical when each kernel execution is short.

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by erhoo82** [comment]
jenkins

**Comment by erhoo82** [comment]
jenkins

**Review by cuichenx — DISMISSED** [review]
LGTM thanks!

**Comment by cuichenx** [comment]
jenkins

**Comment by erhoo82** [comment]
@ericharper
Please review this PR.

**Comment by ericharper** [comment]
Just waiting on internal CI tests. They look good so far. We'll most likely merge first thing tomorrow.

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

Ran nemo-ci as well and all tests passed.

**Pull request merged**
