### PR TITLE
Fix CPU Initialization and TP>1 for LoRA Merge Script

### PR DESCRIPTION
**Pull request by cuichenx**
# What does this PR do ?

Fix 1) merging on CPU, in cases where a GPU is not available, and 2) merging a LoRA model trained with TP>1 into a base model in the distributed checkpointing format.

Tested on Llama2-7b + TP {1, 2, 4} LoRA ckpt, with cpu and gpu options

# Usage

Merging on GPU/CPU can be controlled by
`trainer.accelerator='cpu' | 'gpu'`

Also, the script should always be run with 
`trainer.devices=1` now for distributed checkpoints. If the model cannot fit into one GPU, use the CPU option.

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by cuichenx** [comment]
jenkins

**Comment by cuichenx** [comment]
jenkins

**Comment by arendu** [comment]
LGTM!

**Review by arendu — APPROVED** [review]

**Comment by cuichenx** [comment]
jenkins

**Pull request merged**
