### PR TITLE
Propagate attention_dropout flag for GPT-3

### PR DESCRIPTION
**Pull request by mikolajblaz**
# What does this PR do ?

Allow changing `attention_dropout` from a config file level in the GPT model

**Collection**: language_model

# Changelog 
- Allow changing `attention_dropout` from a config file level in GPT

# Usage
Set `model.attention_dropout` in GPT config file

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by mikolajblaz** [comment]
Do we want to add a default for `attention_dropout` in `examples/nlp/language_modeling/conf/megatron_gpt_config.yaml` too?

**Comment by okuchaiev** [comment]
> Do we want to add a default for `attention_dropout` in `examples/nlp/language_modeling/conf/megatron_gpt_config.yaml` too?

yes please

**Comment by mikolajblaz** [comment]
> > Do we want to add a default for `attention_dropout` in `examples/nlp/language_modeling/conf/megatron_gpt_config.yaml` too?
> 
> yes please

@okuchaiev done

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
