### PR TITLE
Online audio augmentation notebook in ASR examples

### PR DESCRIPTION
**Pull request by titu1994**
# Changelog
## Addition
 - Example notebook which shows the different augmentations that are currently available, how to instantiate them and use them in the ASR data loaders.
 - Also show how to create custom augmentations and register them with NeMo

### CODE REVIEW

**Comment by blisc** [comment]
Can you add a small blurb under each section: `White Noise Perturbation`, `Gain Perturbation`, `
Shift Perturbation`, and `Noise Augmentation` explaining what each perturbation does?

**Comment by titu1994** [comment]
Yeah that would be a good idea to explain what the Perturbation does. Good point.

**Comment by titu1994** [comment]
Rebased with master and added comments as to how the simpler augmentations work and what should be the effect heard by the listener for the above listed augmentations.

**Comment by blisc** [comment]
Minor issue. Github and Colab shows your notebook like so:
```White Noise perturbation is performed by the following steps : 1) Randomly sample the amplitude of the noise from a uniformly distributed range (defined in dB)```
Can you change it so there is a line break, like so:
```
White Noise perturbation is performed by the following steps :
1) Randomly sample the amplitude of the noise from a uniformly distributed range (defined in dB)
```

**Comment by titu1994** [comment]
Fixed by explicitly adding a `<br>` tag after those comments. Seems Jupyter lab processes the beginning of lists with new lines automatically, but github and colab dont.

**Comment by titu1994** [comment]
Thanks for the review!

**Pull request merged**
