### PR TITLE
add knobs for rope/swiglu fusion

### PR DESCRIPTION
**Pull request by lhb8125**
# What does this PR do ?

Add knob for rope fusion
Add knob for swiglu fusion
Change knob for bias_gelu fusion

The PR is related to the PR of MLM: https://gitlab-master.nvidia.com/ADLR/megatron-lm/-/merge_requests/984

**Collection**: [NLP]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage

- set `model.apply_rope_fusion: true` to enable rope fusion

- set `model.bias_activation_fusion: true` to enable bias+activation fusion, which works for both gelu and swiglu type.

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by erhoo82 — APPROVED** [review]

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
Jenkins

**Comment by ericharper** [comment]
jenkins

**Pull request merged**
