### PR TITLE
num_workers default number change

### PR DESCRIPTION
**Pull request by Jorjeous**
Signed-off-by: George Zelenfroynd gzelenfroind@nvidia.com
# What does this PR do ?

added lines to asr models that have no num_worker param, its absence caused slow training

**Collection**: ASR

# Changelog 
- Adds lines in files of asr models

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  

**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by Jorjeous** [comment]
author : gzelenfroind@nvidia.com

**Review by Jorjeous — COMMENTED** [review]
Signed-off-by: George Zelenfroynd [gzelenfroind@nvidia.com](mailto:gzelenfroind@nvidia.com)

**Review by Jorjeous — COMMENTED** [review]
Signed-off-by: George Zelenfroynd gzelenfroind@nvidia.com

**Review by Jorjeous — COMMENTED** [review]
Signed-off-by: George Zelenfroynd gzelenfroind@nvidia.com

**Review by Jorjeous — COMMENTED** [review]
Signed-off-by: George Zelenfroynd gzelenfroind@nvidia.com

**Comment by Jorjeous** [comment]
Signed-off-by: George Zelenfroynd gzelenfroind@nvidia.com

**Comment by titu1994** [comment]
Closing and reopening the PR wont help here.. you need to probably create a fresh PR based on main branch with the fixes. In general, try to rebase every week against the main branch to keep your branch fresh.

**Pull request closed without merging**
