### PR TITLE
Add citation

### PR DESCRIPTION
**Pull request by ericharper**
# What does this PR do ?

Adds CITATION.eff file

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by titu1994 — DISMISSED** [review]
Thanks !

**Review by okuchaiev — APPROVED** [review]

**Review by XuesongYang — APPROVED** [review]
Thanks! Shall we add a DOI (e.g. from Zenodo) to our repo? It would make it easier to reference in academic literature. Guidance is here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by titu1994** [comment]
No to DOI - it archives the entire repo- no longer can push commits to it v

**Review by titu1994 — APPROVED** [review]
Thanks !

**Comment by titu1994** [comment]
Info about repo archiving - https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Pull request merged**
