### PR TITLE
Add tutorial on using Label Studio with NeMo ASR model

### PR DESCRIPTION
**Pull request by niklub**

### CODE REVIEW

**Review by okuchaiev — APPROVED** [review]
thanks!

**Comment by okuchaiev** [comment]
Can you please sign your committed commits? See DCO's bot output how to sign already committed commits  https://github.com/NVIDIA/NeMo/pull/1767/checks?check_run_id=1925053254

**Comment by okuchaiev** [comment]
also, please re-base on the latest main, because currently CI does not pass due to a bug (which was fixed) in older version of main

**Comment by blisc** [comment]
Can you allow us write access to this PR? We can't merge unless your branch is up to date with main and we update main many times a day

**Pull request merged**
