### PR TITLE
Log audio file on loading errors

### PR DESCRIPTION
**Pull request by piraka9011**
Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

It would be helpful to know offending audio files that fail to load if they are corrupt and/or not supported.

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
LGTM, thanks for the contribution !

**Comment by titu1994** [comment]
Seems theres some formatting errors, could you run `python setup.py style --scope nemo --fix`

**Comment by titu1994** [comment]
This PR will be merged into another PR (https://github.com/NVIDIA/NeMo/pull/2240) due to inactivity. One difference is that it will not raise the error, but instead simply log that the file was not loaded properly.

**Comment by piraka9011** [comment]
Got it, sorry for the delay and thanks for the followup!

**Comment by titu1994** [comment]
Thanks for the PR! Normally I'd wait, but this PR would have merge conflicts with that one so it would be easier to integrate into that one.

**Pull request closed without merging**
