### PR TITLE
[NeMo-UX] Set parallelism correctly when using VPP

### PR DESCRIPTION
**Pull request by marcromeyn**
# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ShriyaPalsamudram** [comment]
@marcromeyn I see that the set parallelism call is missing, here's the commit we have been using https://github.com/NVIDIA/NeMo/commit/e6d34effeea37e0def50dbfc3907ee2505165b50 

Is that something you can add to this PR?

**Comment by marcromeyn** [comment]
@ShriyaPalsamudram It seems a recent commit has changed that implementation, this PR should do the same thing

**Review by maanug-nv — APPROVED** [review]
LGTM

**Comment by ShriyaPalsamudram** [comment]
@marcromeyn great thanks, that addresses my concern. LGTM

**Review by ShriyaPalsamudram — APPROVED** [review]

**Pull request merged**
