### PR TITLE
[NLP] Use register_artifact from superclass directly

### PR DESCRIPTION
**Pull request by janekl**
# What does this PR do ?

Removes explicit code to call superclass method (cleanup).

**Collection**: [NLP]

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] Improvement

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to https://github.com/NVIDIA/NeMo/pull/7935

### CODE REVIEW

**Comment by ericharper** [comment]
I don't know why we need this. It breaks a bunch of things at this point. Is it worth it to change it?

**Review by titu1994 — COMMENTED** [review]
This is probably ok but @ericharper for approval

**Comment by titu1994** [comment]
jenkins

**Comment by janekl** [comment]
Eric pointed out that default for `verify_src_exists` is different across the two classes, which I missed. Hence pipeline fails.

I'll figure that out as I think it's worth it as a simplification

**Pull request closed without merging**
