### PR TITLE
Add conformer post attn and non pos_emb

### PR DESCRIPTION
**Pull request by ArtyomZemlyak**
# What does this PR do ?

Add post attention for conformer and off pos_emb computation

**Collection**: ASR

# Changelog 
- Using prefix `post_` for all `self_attention_model` options will move attention after conv
- New `non_pos` option for `self_attention_model` for off computation of positional emb

# Usage
* You can potentially add a usage example below

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ArtyomZemlyak** [comment]
@titu1994 
Hi!
Can you review?

**Comment by titu1994** [comment]
Could you explain what is the motivation of this pr? Is this some paper implementation? These are significant changes and need to be reviewed if it's necessary to add to the general conformer block or subclass it out

**Comment by ArtyomZemlyak** [comment]
@titu1994 
Its proposed in this paper: [A Better and Faster End-to-End Model for Streaming ASR](https://arxiv.org/abs/2011.10798):

> Additionally, we speedup the training and inference by remov-
ing the original relative positional encoding [24]. Instead, we reuse
the existing convolution module that aggregates information from
neighboring context to implicitly provide relative positional infor-
mation [24, 25]. This is done by simply swapping the order of the
convolution module and the multi-head self-attention module, lead-
ing to the improved Conformer block

**Comment by titu1994** [comment]
I read the paper. The modifications here are too severe to add to the normal conformer - having to hack around the positional encoding and move around blocks is a no go. 

It's also been two years and there's been no follow up work on this work, and no significant ablation tests were done to show if this is even an effective change that doesn't hurt WER. 

To be safe, we can have a clone of the conformer model with the required changes, but we cannot modify the current Conformer for this papers implementation.

**Pull request closed without merging**
