### PR TITLE
Bugfix for BF16 grad reductions with distopt

### PR DESCRIPTION
**Pull request by timmoon10**
# What does this PR do ?

https://github.com/NVIDIA/NeMo/pull/5920 adds support for BF16 grad reductions with distopt, with embedding grad reductions done in FP32. @mikolajblaz found some bugs and it turns out the FP32 reductions were not being done at all. This PR fixes those issues. When I run GPT-3 175B, I confirm the embedding grads are now optimized with the FP32 optimizer. Loss values are the same with FP32 and BF16 grad reductions, up to 50 steps and within numerical accuracy.

This turned out messier than I would have liked. It would have been better to integrate distopt support for multiple grad dtypes into Apex.

**Collection**: NLP

# Changelog 
- Debug distopt support for BF16 grad reductions

# Usage

Set the optimizer to `distributed_fused_adam` in the config file:

https://github.com/NVIDIA/NeMo/blob/aaa0ccacf5b4d204ed18f6052e55ff6f20575996/examples/nlp/language_modeling/conf/megatron_gpt_config.yaml#L207

Configure the optimizer with `grad_sync_dtype: bf16`.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Fixes bugs from https://github.com/NVIDIA/NeMo/pull/5920
* Depends on https://github.com/NVIDIA/apex/pull/1575
* Depends on https://github.com/NVIDIA/TransformerEngine/pull/75

### CODE REVIEW

**Comment by mikolajblaz** [comment]
I noticed that the FP32 model "main" params are not dumped in the checkpoint nor restored.
It means that in the 1st optimizer step after checkpoint loading, model params are overwritten with garbage.

@timmoon10 you can choose to implement it however you think it's appropriate, but [here is an example fix](https://github.com/NVIDIA/NeMo/commit/bb5237dc4c38bce18be60e31ddcdf668b94c36ad), it's quite simplistic but I think it will cover all scenarios. Notice that I didn't test it on regular checkpoints, but it does work with some distributed checkpoint additions on the mlperf side.

With that fix training looks correct on a small scale, I've just started a few full trainings to verify convergence e2e.

**Comment by timmoon10** [comment]
Thanks for the catch @mikolajblaz, I've taken your commit. I've also rebased this commit into `r1.17`.

**Comment by mikolajblaz** [comment]
Thanks. I managed to run 1 mlperf training and the convergence is fine: [TB](http://llmtb.nvidia.com:6018/?tagFilter=lm+loss+validation%24&smoothing=0&runColorGroup=run&runFilter=%28M13%2Fselene%2F%7CM13_5%29.*_s5657.*megatron#timeseries)

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
