### PR TITLE
Information Retrieval Tutorial

### PR DESCRIPTION
**Pull request by AlexGrinch**

### CODE REVIEW

**Comment by okuchaiev** [comment]
@AlexGrinch  can you please fix the PR so that CI passes

**Review by tkornuta-nvidia — APPROVED** [review]
Generally looks good to me. Why CI is failing?

**Comment by okuchaiev** [comment]
@AlexGrinch code style

**Comment by okuchaiev** [comment]
please fix code formatting to unblock CI:
```
python setup.py style --fix
```

**Pull request merged**
