### PR TITLE
Revert "adding OnlineSampleMapping"

### PR DESCRIPTION
**Pull request by pablo-garay**
Reverts NVIDIA/NeMo#8137

Nemo pipeline is broken (finetune tests failing) due to this. Hence revert.

More context/details:
- two gpt3 fine-tunning tests failed on EOS (finetune.gpt3.126m_tp1_pp1_1node_100steps_squad and finetune.gpt3.400m_improved_tp1_pp1_1node_100steps_squad). Check out the error log, it’s not the fault of context parallelism. The error comes from dataset, which is introduced by this PR https://github.com/NVIDIA/NeMo/pull/8137

[10:43](https://nvidia.slack.com/archives/D062J0U5PJ8/p1705084988269489)

Above problematic PR was merged after my context parallelism PR. So for sanity check, I also ran a pipeline with the NeMo commit ID of context parallelism merging (i.e., without above problematic PR) https://gitlab-master.nvidia.com/dl/JoC/nemo-ci/-/pipelines/12047711
you can see those two fine-tuning test passed, so I think context parallelism code works fine

### CODE REVIEW

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Comment by ericharper** [comment]
jenkins

**Comment by arendu** [comment]
Is there a CI test which uses context parallel? @pablo-garay @ericharper 
cc @michalivne

**Comment by pablo-garay** [comment]
> Is there a CI test which uses context parallel? @pablo-garay @ericharper cc @michalivne

Yes, there is now. I merged yesterday tests made by @xrennvidia

**Comment by pablo-garay** [comment]
jenkins

**Comment by xrennvidia** [comment]
> Is there a CI test which uses context parallel? @pablo-garay @ericharper cc @michalivne

Hi @arendu as said in the first comment of this PR, the failed tests are not CP tests, they are fine-tuning test, [you can see their error logs in this CI pipeline](https://gitlab-master.nvidia.com/dl/JoC/nemo-ci/-/pipelines/12053377).

**Comment by arendu** [comment]
@pablo-garay thanks for adding context parallel tests to the CI as well. could you point me to the exact CI test?

**Comment by arendu** [comment]
@xrennvidia yes but w/o CI its hard to debug/iterate on the PR.

**Comment by xrennvidia** [comment]
> @xrennvidia yes but w/o CI its hard to debug/iterate on the PR.

OK, I think @pablo-garay can tell you how to run NeMo-CI.

**Comment by pablo-garay** [comment]
> @xrennvidia yes but w/o CI its hard to debug/iterate on the PR.

You can run here: https://gitlab-master.nvidia.com/dl/JoC/nemo-ci/-/pipelines/new . Set variables:
NEMO_COMMIT: your commit hash w/ your changes
TESTS_TO_RUN_ON_THIS_COMMIT: nightly

image

**Comment by arendu** [comment]
@pablo-garay oh maybe i misunderstood, when you said you added a test that uses context parallel i was hoping you can add it to the Github CI tests like this one for example: https://github.com/NVIDIA/NeMo/blob/199a8baf2859496e127771ffb4f64efb2767ec35/Jenkinsfile#L3797

**Comment by pablo-garay** [comment]
> @pablo-garay oh maybe i misunderstood, when you said you added a test that uses context parallel i was hoping you can add it to the Github CI tests like this one for example:
> 
> https://github.com/NVIDIA/NeMo/blob/199a8baf2859496e127771ffb4f64efb2767ec35/Jenkinsfile#L3797
> 
> These aren't full tests (they dont check for convergence) just test if functionality breaks.

@xrennvidia added the tests. I work on NemoCI, not on context parallel . He's main PIC for context parallel discussion.
So yeah these tests check functionality, and might not other aspects e.g. convergence.
What I can say is that the change broke our already pre-existing tests (added long time ago) which were working fine before - so that is why it needs to be fixed/reverted.

**Comment by pablo-garay** [comment]
jenkins

**Pull request merged**
