### PR TITLE
a quick fix for issue #3094 index out-of-bound when truncating long text to max_seq_length

### PR DESCRIPTION
**Pull request by bugface**
@okuchaiev

This is a PR for fixing issue #3094 where the index will be out-of-bound when truncating long text ext to max_seq_length in text_classification_dataset.py

Signed-off-by: bugface <alexgre@ufl.edu>

### CODE REVIEW

**Review by VahidooX — CHANGES_REQUESTED** [review]
LGTM, thanks for fixing the bug!
You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.

**Comment by bugface** [comment]
> LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.

The output from running python setup.py style --fix:

"""
All done! ✨ 🍰 ✨
350 files reformatted, 609 files left unchanged.
FAIL
"""

**Comment by VahidooX** [comment]
> 
> 
> > LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.
> 
> The output from running python setup.py style --fix:
> 
> """ All done! ✨ 🍰 ✨ 350 files reformatted, 609 files left unchanged. FAIL """

It looks like the styling script has changed 350 files! I have no idea why it has happened. Would you please revert it back to the previous commit.? I will try to fix the style for just that specific file.

**Comment by bugface** [comment]
> > > LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.
> > 
> > 
> > The output from running python setup.py style --fix:
> > """ All done! ✨ 🍰 ✨ 350 files reformatted, 609 files left unchanged. FAIL """
> 
> It looks like the styling script has changed 350 files! I have no idea why it has happened. Would you please revert it back to the previous commit.? I will try to fix the style for just that specific file.

I will revert to commit 246960 and fix the style just for the py script I changed.

**Comment by VahidooX** [comment]
> 
> 
> > > > LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.
> > > 
> > > 
> > > The output from running python setup.py style --fix:
> > > """ All done! ✨ 🍰 ✨ 350 files reformatted, 609 files left unchanged. FAIL """
> > 
> > 
> > It looks like the styling script has changed 350 files! I have no idea why it has happened. Would you please revert it back to the previous commit.? I will try to fix the style for just that specific file.
> 
> I will revert to commit 246960 and fix the style just for the py script I changed.

Not sure what is wrong with your code styling process but its result is different from what it should be. As you see, there are a lot of changes in the file. You may revert it back to the original file and just replace this specific line with the same exact style:

`                sent_subtokens = sent_subtokens[: max_seq_length - 1]
`

**Comment by VahidooX** [comment]
> 
> 
> > > > > LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.
> > > > 
> > > > 
> > > > The output from running python setup.py style --fix:
> > > > """ All done! ✨ 🍰 ✨ 350 files reformatted, 609 files left unchanged. FAIL """
> > > 
> > > 
> > > It looks like the styling script has changed 350 files! I have no idea why it has happened. Would you please revert it back to the previous commit.? I will try to fix the style for just that specific file.
> > 
> > 
> > I will revert to commit 246960 and fix the style just for the py script I changed.
> 
> Not sure what is wrong with your code styling process but its result is different from what it should be. As you see, there are a lot of changes in the file. You may revert it back to the original file and just replace this specific line with the same exact style:
> 
> ` sent_subtokens = sent_subtokens[: max_seq_length - 1]`

Also, you need to pull from the main again.

**Comment by bugface** [comment]
> > > > > > LGTM, thanks for fixing the bug! You just need to run "python setup.py style --fix" in the repo folder to fix the style of the code.
> > > > > 
> > > > > 
> > > > > The output from running python setup.py style --fix:
> > > > > """ All done! ✨ 🍰 ✨ 350 files reformatted, 609 files left unchanged. FAIL """
> > > > 
> > > > 
> > > > It looks like the styling script has changed 350 files! I have no idea why it has happened. Would you please revert it back to the previous commit.? I will try to fix the style for just that specific file.
> > > 
> > > 
> > > I will revert to commit 246960 and fix the style just for the py script I changed.
> > 
> > 
> > Not sure what is wrong with your code styling process but its result is different from what it should be. As you see, there are a lot of changes in the file. You may revert it back to the original file and just replace this specific line with the same exact style:
> > ` sent_subtokens = sent_subtokens[: max_seq_length - 1]`
> 
> Also, you need to pull from the main again. Thanks!

sry for the weird style behavior; fix the style just for that line and merged the main

**Review by VahidooX — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
