### PR TITLE
Fix configs in ASR tutorials

### PR DESCRIPTION
**Pull request by fayejf**
Update and fix the **outside of the model constructor configs** in ASR tutorials. Converting outside Hydra 0.x configs to Hydra 1.x configs.
Tiny bug fix for notebook 03 speech command

Related bug: [1649](https://github.com/NVIDIA/NeMo/issues/1649)

### CODE REVIEW

**Review by titu1994 — CHANGES_REQUESTED** [review]
LGTM but revert branch to b3.

**Comment by titu1994** [comment]
Hmm wait, the function exists in main but the error exists in b3? If the error exists only in main, then for now comment out these patches with a note that it needs to be uncommented

**Comment by fayejf** [comment]
> Hmm wait, the function exists in main but the error exists in b3? If the error exists only in main, then for now comment out these patches with a note that it needs to be uncommented. Or use a try catch.
> 
> Also, tests are failing on a notebook only pr?

@titu1994 the error exists in b3 well the patch function exists in main. Is it safe to change branch in some notebooks to main now?  If it's not, I can revert it back to b3 and fix it by manually accessing params or writing the patch function explicitly in notebooks. 

Right not sure why the tests fails for notebook changes

**Comment by titu1994** [comment]
We will be changing branch later, main is not suitable for the notebooks cause it's not stable and tested as much as the exact branches.

For now, It might be best to do manual fixes by back porting the config updater to the notebooks.

**Comment by fayejf** [comment]
> We will be changing branch later, main is not suitable for the notebooks cause it's not stable and tested as much as the exact branches.
> 
> For now, It might be best to do manual fixes by back porting the config updater to the notebooks.

Sounds great. will update it.

**Review by titu1994 — APPROVED** [review]
@fayejf LGTM

**Pull request merged**
