### PR TITLE
Add REST service requirements.txt

### PR DESCRIPTION
**Pull request by oyilmaz-nvidia**
# What does this PR do ?

Add a new requirements.txt for the REST service dependencies

### CODE REVIEW

**Review by athitten — DISMISSED** [review]
LGTM, thanks!

**Review by artbataev — CHANGES_REQUESTED** [review]
Please, adjust Dockerfile (Dockerfile.speech) accordingly to avoid installing these requirements
`vllm` breaks the docker container build due to hardcoded requirements for torch

https://github.com/NVIDIA/NeMo/blob/r2.0.0rc1/Dockerfile#L134

**Review by artbataev — APPROVED** [review]
Thanks a lot! This will help to save the docker build, which has just been fixed)

**Comment by pablo-garay** [comment]
ci passed : https://github.com/NVIDIA/NeMo/actions/runs/10114455695

**Review by pablo-garay — APPROVED** [review]

**Pull request merged**
