### PR TITLE
Fix RANK env variable check in global rank check

### PR DESCRIPTION
**Pull request by PeganovAnton**
Signed-off-by: PeganovAnton <peganoff2@mail.ru>

### CODE REVIEW

**Review by okuchaiev — APPROVED** [review]
@titu1994 and @ericharper looks like we had a bug which Anton fixed. Please double-check, but looks good to me

**Review by titu1994 — APPROVED** [review]
Lgtm, but what does this impact ?

**Comment by titu1994** [comment]
Btw @okuchaiev this PR does the same thing - https://github.com/NVIDIA/NeMo/pull/3374

**Comment by blisc** [comment]
Merged the other PR

**Pull request closed without merging**
