### PR TITLE
Added check for microbatch calculator

### PR DESCRIPTION
**Pull request by vadam5**
Signed-off-by: Virginia Adams <vadams@nvidia.com>

Checks if micro batch calculator has already been initialized before calling apex  micro batch setup function. 

**Collection**: BigNLP

# Changelog 
- Changed megation_init.py

# Usage
N/A

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
- [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [X] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by MaximumEntropy — APPROVED** [review]
LGTM!

**Review by MaximumEntropy — CHANGES_REQUESTED** [review]
I think we'd need to try and see if the user is trying to setup the microbatch calculator for the second time with different args and if so, throw an error.

**Review by MaximumEntropy — APPROVED** [review]
LGTM!

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

We need to request a feature from Apex that let's us destroy _GLOBAL_NUM_MICROBATCHES_CALCULTAOR.

**Pull request merged**
