### PR TITLE
Added option to get log probs in ASR transcribe

### PR DESCRIPTION
**Pull request by vsl9**
Signed-off-by: Vitaly Lavrukhin <vlavrukhin@nvidia.com>

### CODE REVIEW

**Review by titu1994 — COMMENTED** [review]
Could this be added to CTC BPE models too ?

**Comment by vsl9** [comment]
@titu1994 sure, CTC BPE models use the same inherited transcribe method, so it already works the same way with them.

**Comment by titu1994** [comment]
Perfect!

**Comment by titu1994** [comment]
@okuchaiev Could you review and signoff ? This goes into main branch

**Comment by okuchaiev** [comment]
sorry, need to re-route this to dev because 1.0.0b1 is already posted to pip. Don't want to bump version in main beyond that until we do a GH release

**Pull request merged**
