### PR TITLE
fixed multi gpu/node checkpoint saving race condition

### PR DESCRIPTION
**Pull request by yzhang123**
Signed-off-by: Yang Zhang <yangzhang@nvidia.com>

### CODE REVIEW

**Comment by blisc** [comment]
What is the race condition?
I can see that this fixes it be splitting the experiment into one directory per rank but why do we want to do this?

**Comment by blisc** [comment]
@yzhang123 if #139 fixes this issue, can we close this PR?

**Comment by okuchaiev** [comment]
@yzhang123 is this now obsolete? If not, could you please re-base on the latest master?

**Comment by okuchaiev** [comment]
looks like this was addressed in #139 closing this. If you disagree @yzhang123 please re-open it but then re-base on the latest master

**Pull request closed without merging**
