### PR TITLE
Add primer notebook on NeMo 1.x, PTL and Hydra/OmegaConf

### PR DESCRIPTION
**Pull request by titu1994**
Primer notebook explaning a few fundamental concepts of NeMo Models, their interaction with config objects - Hydra and OmegaConf, and minor details regarding interop with PTL. 

Will be followed by a second notebook which explains train, eval, test setup pertaining more to PTL than Hydra and OmegaConf

### CODE REVIEW

**Comment by ekmb** [comment]
@titu1994 this is great, thanks for doing this!
A few comments/suggestions up to you whether to act on them:
1. How about adding CV and Common collections to the list of available collections and give their brief description for consistency?
2. Maybe be in the `NeMo with Hydra` part add a link to our examples folder and describe its structure: all models have associated configs released + script to train the model + some models (common for NLP) have data folders to do some data preprocessing 
3. This is an amazing tutorial though it might be too much for a first time user. How about from `Analysing the contents of the Model config` part go directly to `NeMo with Hydra` - so that users can just start training our examples quickly. And put the rest of the parts at the end for more advanced users?
4. Tiny typos in: '... peridically save ...' and 'flag, whic will offer '
5. Are we going to add pieces of this tutorial to the docs?

**Comment by titu1994** [comment]
@ekmb Good points, I'll address them below

1) CV kinda breaks all of the consistency argument, cause it doesn't use config files, uses a special decorator, config objects etc. I think we can spin it off into its own notebook (in the future) when we more robustly support config class based action. @tkornuta-nvidia what is your opinion on this ? The commons collections are rarely used by end users - it holds stuff like losses and tokenizers, which go into the model but is not a Model itself. So I chose to keep it out of the "collections" we show to the user. There is a case for explaining them, but it's for more advanced users who are building their own Models, not in the primer. 

2) Good point. I'll add that. 

3) Well I would say a primer is a thorough explanation of all the things that are immediately important when using Nemo - how to modify models is essential task in all 4 domains, so is saving restoring, etc. So imo they should remain part of the primer. @okuchaiev Do you also feel like we should spin this part off into its own notebook ?

4) For grammar, could you edit the colab directly, I'll just update the notebook here with the final version there. 

5) I'm hoping so. Or at least rediriect users to this primer so that they can jump start with Nemo.

**Comment by ekmb** [comment]
@titu1994 
on 3. Not necessarily move in a separate notebook, maybe just create Part I and Part II within this tutorial? Maybe also move saving and restoring models part to the beginning - just make it easy and clear how to run with the default configs

**Comment by titu1994** [comment]
Oh ok that makes sense. But this isn't the train or inference script, those will go into another notebook. I'll reorder and consider what would be better

**Comment by tkornuta-nvidia** [comment]
> 1. CV kinda breaks all of the consistency argument, cause it doesn't use config files, uses a special decorator, config objects etc. I think we can spin it off into its own notebook (in the future) when we more robustly support config class based action. @tkornuta-nvidia what is your opinion on this ? The commons collections are rarely used by end users - it holds stuff like losses and tokenizers, which go into the model but is not a Model itself. So I chose to keep it out of the "collections" we show to the user. There is a case for explaining them, but it's for more advanced users who are building their own Models, not in the primer.

Ad. CV: correct, it is different, generally there should be an effort made towards unification. Still, waiting for [PTL PR with hydra](https://github.com/PyTorchLightning/pytorch-lightning/pull/2639) to be merged in the first place.

Ad. Common: "The commons collections are rarely used by end users" - Why is that? Who is your "end user"? Generally I think it should be the opposite, Common, by definition, should contain things that are used commonly, across all domains/modalities.

And as we are on this topic - I am not sure whether e.g. tokenizers should be in common, for me they clearly belong to NLP domain.

**Comment by titu1994** [comment]
Ok so we'll keep CV seperate for the time being. 

Common does not contain any Model. We don't have a Common model, so much as we have ASR Models, NLP Models, TTS and CV Models (I classify model as anything that inherits ModelPT, all else is a Module). 

In that sense, end users interact directly with Models as their first approach in the primer - an end to end system for a certain domain for a certain task, entirely containing all components required to function immediately. 

We also have end users who develop said models, which will then of course require common components such as losses and metrics and even stuff like tokenizers sometimes. So that's what I meant by there's a case for explaining them, just in a different context - when developing models from the ground up, not direct usage of pre built ones. 

Re: tokenizers should be in NLP, I disagree. Tokenizers are already used by ASR, and I don't want to have the full dependency of importing all of NLP just to get tokenizer support. It rightfully belongs in the common domain.

**Comment by titu1994** [comment]
@ekmb Updated the colab to include the sections "NeMo Examples" and "NeMo Tutorials" before "NeMo with Hydra". I could fill up ASR well enough, but I'll need nlp teams help to fill out the NLP subsection more. @blisc Ill need your help to add to the TTS section.

Upon thinking how to reorder the content, I think its best to separate the primer into a few phases. 

This one is a primer on what a nemo model is and how to interact with it after restoration + general NeMo code organization.

We will have a primer on how to construct a NeMo model for a task from scratch. 

Finally a primer on the general gist of how to train, eval using PTL Trainer, with experiment manager support and save to tarfile format etc.

**Comment by okuchaiev** [comment]
also, could you please link to it in README.rst before other tutorials ?

**Comment by titu1994** [comment]
Oh that sounds like a good plan, yes I'll put examples and tutorial last then and hydra above those two. One last thing is that I just realised that well need to eventually update the headers of all of our notebooks to point to main branch so I'll do that fix too.

**Comment by titu1994** [comment]
Before merging let's wait for NLP and TTS members to update their sections inside the examples subsection. TTS is quite difficult to elaborate on, at least nlp could be bullet pointed

**Comment by titu1994** [comment]
@okuchaiev Notebook is ready to merge once tests pass. Updated readme.rst and it contains the changes from the colab notebook.

**Pull request merged**
