### PR TITLE
fix the text classification labels_file artifact.

### PR DESCRIPTION
**Pull request by VahidooX**

### CODE REVIEW

**Review by zeyuznv — APPROVED** [review]
@ericharper please have this PR ported to r1.3.0 branch.

**Comment by ericharper** [comment]
r.1.3.0 is already out but we can do a dot release: r1.3.1. Does that work for you @zeyuznv ?

**Comment by zeyuznv** [comment]
Yes, thanks!
________________________________

**Review by ekmb — APPROVED** [review]

**Comment by zeyuznv** [comment]
> r.1.3.0 is already out but we can do a dot release: r1.3.1. Does that work for you @zeyuznv ?

Yes thanks! @ericharper

**Pull request merged**
