### PR TITLE
mcore ds fix

### PR DESCRIPTION
**Pull request by dimapihtar**
# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by dimapihtar** [comment]
jenkins

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Comment by pablo-garay** [comment]
Thanks Dmytro!

**Comment by ryxli** [comment]
Was this able to launch a job successfully? If so, what version of Megatron-LM was used? 
I see the commit in the base Dockerfile is 27cbe46714a50c43ed290f1b1472db8d2780c55c, which is on the core_r0.4.0 branch. 

But the addition of GPTDatasetConfig in megatron.core.datasets.gpt_dataset only exists on main, and for reset_position_ids and etc only after this commit: https://github.com/NVIDIA/Megatron-LM/commit/8d8241a9cfdf5ad6c511c5303a2623185ee18c3c

I'm wondering where eod_id comes from since it's passed as part of all kwargs into GPTDatasetConfig.
But I don't see eod_id existing in gpt_dataset in Megatron-LM https://github.com/NVIDIA/Megatron-LM/blame/4bd4e7426c8def582eb80ae53f296a803643d2f5/megatron/core/datasets/gpt_dataset.py#L33

Currently I'm having issues launching the job:
```
  File "lib/python3.10/site-packages/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py", line 1223, in build_train_valid_test_datasets
    dataset_config = GPTDatasetConfig(**kwargs)
TypeError: GPTDatasetConfig.__init__() got an unexpected keyword argument 'eod_id'
```

**Pull request merged**
