### PR TITLE
LaserTagger Integration

### PR DESCRIPTION
**Pull request by yashnv**

### CODE REVIEW

**Comment by okuchaiev** [comment]
please sign your commits (see DCO's output on how to sign already signed commits. for new one just do "git commit -s ..." when committing).
Also, make sure that CI passes - currently it fails on stylecheck.
To fix style automatically do: "python setup.py style --fix"

**Comment by okuchaiev** [comment]
please sign your commits (do "git commit -s ..." when committing)
check DCO's bot output to see how to sign already committed commits. Also the CI is failing. Do your tests pass locally ?

**Comment by yashnv** [comment]
I signed the commits twice using those steps, but I don't know why the DCO tests are still failing.

**Comment by okuchaiev** [comment]
is this still a draft PR?

**Comment by yashnv** [comment]
@okuchaiev should close this one, I am planning to open a new one later today. For some reason I can't sign the first commit.

**Pull request closed without merging**
