### PR TITLE
Fix bug of CTCLoss in Transfer Learning.

### PR DESCRIPTION
**Pull request by Honghe**
Create new CTCLoss to use new_vocabulary from new decoder.

### CODE REVIEW

**Review by okuchaiev — APPROVED** [review]
Thank you for bugfix!

Before we merge, could you please sign your commit - it is easy (and a legal requirement for us), DCO's bot output shows how: 
https://github.com/NVIDIA/NeMo/pull/1178/checks?check_run_id=1127131279

**Comment by okuchaiev** [comment]
@titu1994 is similar fix need in EncDecCTCBPEModel ?

**Comment by titu1994** [comment]
Yes it's required there too

**Comment by Honghe** [comment]
@okuchaiev I have signed the commit, but it seems something still wrong.

**Pull request merged**
