### PR TITLE
Multi Node Fix

### PR DESCRIPTION
**Pull request by blisc**
Should be a more general fix that covers issues presented in #136 and #130

### CODE REVIEW

**Comment by blisc** [comment]
@khcs @yzhang123 @okuchaiev Can you try multi node training with this PR and see if checkpointing or other multi-node issues still persist?

**Comment by okuchaiev** [comment]
tried. still getting this kind of error:

2019-11-22 13:20:30,630 - INFO - Restoring JasperEncoder from ./JasperEncoder-STEP-10500.pt
Traceback (most recent call last):
  File "eval.py", line 104, in <module>
    main()
  File "eval.py", line 93, in main
    cache=True
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/core/neural_factory.py", line 599, in infer
    offload_to_cpu=offload_to_cpu)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/backends/pytorch/actions.py", line 1370, in infer
    mod.restore_from(checkpoint, self._local_rank)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/nemo/backends/pytorch/nm.py", line 106, in restore_from
    self.load_state_dict(t.load(path, map_location=load_device))
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 256 got 65536

**Comment by blisc** [comment]
Did you retrain your model or are you trying to load a pretrained checkpoint? Older models trained prior to this fix will not and mostly likely will never work.

**Comment by okuchaiev** [comment]
I was training using this commit id: 78c676ab209cc584f04366ad28335c154bf2d34f  re-loading using 0.8.2

**Pull request merged**
