### PR TITLE
chore: minor cleanup

### PR DESCRIPTION
**Pull request by messiaen**
# What does this PR do ?

Minor cleaning, followup from #5837 

@VahidooX I think I've address you comments. Let me know if I missed something.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

@VahidooX 

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by VahidooX — DISMISSED** [review]
please add max_dim argument to the original get_initial_cache_state in the StreamingEncoder class.

**Review by VahidooX — DISMISSED** [review]

**Comment by jvcrnc** [comment]
There is still a problem with this onnx export 
  File "C:\NeMo-cleanup-cache-aware\nemo\collections\asr\parts\submodules\causal_convs.py", line 142, in update_cache
    cache_next[self._cache_id, :, :, -cache_keep_size:] = x[:, :, :cache_keep_size]
RuntimeError: The expanded size of the tensor (30) must match the existing size (63) at non-singleton dimension 2.  Target sizes: [1, 512, 30].  Tensor sizes: [512, 63]

**Comment by VahidooX** [comment]
> There is still a problem with this onnx export File "C:\NeMo-cleanup-cache-aware\nemo\collections\asr\parts\submodules\causal_convs.py", line 142, in update_cache cache_next[self._cache_id, :, :, -cache_keep_size:] = x[:, :, :cache_keep_size] RuntimeError: The expanded size of the tensor (30) must match the existing size (63) at non-singleton dimension 2. Target sizes: [1, 512, 30]. Tensor sizes: [512, 63]
> 
> Before there was code in causal_convs.py to prevented this issue, but for some reason it was removed.

Would you please send a reference to the exact lines which are dropped?

**Review by VahidooX — APPROVED** [review]

**Comment by jvcrnc** [comment]
> > There is still a problem with this onnx export File "C:\NeMo-cleanup-cache-aware\nemo\collections\asr\parts\submodules\causal_convs.py", line 142, in update_cache cache_next[self._cache_id, :, :, -cache_keep_size:] = x[:, :, :cache_keep_size] RuntimeError: The expanded size of the tensor (30) must match the existing size (63) at non-singleton dimension 2. Target sizes: [1, 512, 30]. Tensor sizes: [512, 63]
> > Before there was code in causal_convs.py to prevented this issue, but for some reason it was removed.
> 
> Would you please send a reference to the exact lines which are dropped?

After my comment code was added to prevent the export issue:
cache_keep_size = torch.clip(cache_keep_size, min=1, max=cache_next.size(-1))

However at runtime using this exported onnx model there is a onnx crash:
Possibly it has to do with onnx tensor having size zero, that it can not handle 
The crash is when the onnx session is created with this model:
Unhandled exception at 0x00007FFEAD4DCD29 in OnnxModel.exe: Microsoft C++ exception: Ort::Exception at memory location 0x0000006BE7AF9270.

**Comment by VahidooX** [comment]
>> Just tested with onnxruntime 14.1 here there is no exception.
So the issue is now fixed?

**Comment by VahidooX** [comment]
> > > There is still a problem with this onnx export File "C:\NeMo-cleanup-cache-aware\nemo\collections\asr\parts\submodules\causal_convs.py", line 142, in update_cache cache_next[self._cache_id, :, :, -cache_keep_size:] = x[:, :, :cache_keep_size] RuntimeError: The expanded size of the tensor (30) must match the existing size (63) at non-singleton dimension 2. Target sizes: [1, 512, 30]. Tensor sizes: [512, 63]
> > > Before there was code in causal_convs.py to prevented this issue, but for some reason it was removed.
> > 
> > 
> > Would you please send a reference to the exact lines which are dropped?
> 
> After my comment code was added to prevent the export issue: cache_keep_size = torch.clip(cache_keep_size, min=1, max=cache_next.size(-1))
> 
> However at runtime using this exported onnx model there is a onnx exception Could not find an implementation for Clip(13) node with name 'Clip_907' exception code 9. I'm using onnxruntime 13.1. Edit: Just tested with onnxruntime 14.1 here there is no exception.

 So the issue is now fixed?

**Comment by jvcrnc** [comment]
> > > > There is still a problem with this onnx export File "C:\NeMo-cleanup-cache-aware\nemo\collections\asr\parts\submodules\causal_convs.py", line 142, in update_cache cache_next[self._cache_id, :, :, -cache_keep_size:] = x[:, :, :cache_keep_size] RuntimeError: The expanded size of the tensor (30) must match the existing size (63) at non-singleton dimension 2. Target sizes: [1, 512, 30]. Tensor sizes: [512, 63]
> > > > Before there was code in causal_convs.py to prevented this issue, but for some reason it was removed.
> > > 
> > > 
> > > Would you please send a reference to the exact lines which are dropped?
> > 
> > 
> > After my comment code was added to prevent the export issue: cache_keep_size = torch.clip(cache_keep_size, min=1, max=cache_next.size(-1))
> > However at runtime using this exported onnx model there is a onnx exception Could not find an implementation for Clip(13) node with name 'Clip_907' exception code 9. I'm using onnxruntime 13.1. Edit: Just tested with onnxruntime 14.1 here there is no exception.
> 
> So the issue is now fixed?

Yes, I still have to adapt my decoder to work with the changed caching, to see if decoding works too.

**Comment by jvcrnc** [comment]
There is still a problem, even the built in verify_runtime fails:
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1530' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:26 onnxruntime::ReshapeHelper::ReshapeHelper i < input_shape.NumDimensions() was false. The dimension with value zero exceeds the dimension size of the input tensor.

**Pull request merged**
