### PR TITLE
Fix overflow error during grid search

### PR DESCRIPTION
**Pull request by dxdydz**
Currently, the code finds e^p every single loop during alpha-beta language model grid search, which can result in NaNs. Moved the e^p processing outside of the loop.

### CODE REVIEW

**Comment by blisc** [comment]
Thank you very much for your bug fix.
Can you sign off your commit? The output of the DCO bot should show you how to do that.
Can you also run `python setup.py style --fix` and then commit the result with signoff `git commit -s ...`?

**Comment by dxdydz** [comment]
> Thank you very much for your bug fix.
> Can you sign off your commit? The output of the DCO bot should show you how to do that.
> Can you also run `python setup.py style --fix` and then commit the result with signoff `git commit -s ...`?

Sure thing.

**Comment by okuchaiev** [comment]
@dxdydz  thanks for your PR.
Did you do: "python setup.py style --fix" ?
The CI is failing (see output below) because of the formatting issue, and "python setup.py style --fix" should fix it automatically.

```
+ test -f /etc/shinit_v2

+ source /etc/shinit_v2

+++ sed -n 's/^NVRM.*Kernel Module *\([^() ]*\).*$/\1/p' /proc/driver/nvidia/version

+++ sed 's/^$/unknown/'

++ NV_DRIVER_VERS=440.59

++ export _CUDA_COMPAT_PATH=/usr/local/cuda/compat

++ _CUDA_COMPAT_PATH=/usr/local/cuda/compat

+++ hostname

++ _CUDA_COMPAT_CHECKFILE=/usr/local/cuda/compat/.440.59.00abec72abb8.checked

++ _CUDA_COMPAT_REALLIB=/usr/local/cuda/compat/lib.real

++ _CUDA_COMPAT_SYMLINK=/usr/local/cuda/compat/lib

++ '[' -n 440.59 -a '!' -e /usr/local/cuda/compat/.440.59.00abec72abb8.checked ']'

++ unset _CUDA_COMPAT_CHECKFILE

++ unset _CUDA_COMPAT_REALLIB

++ unset _CUDA_COMPAT_SYMLINK

+ '[' -z '' ']'

+ return

+ python setup.py style

running style

Running command: isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=119 -rc -ws . --check --diff

Skipped 5 files

Running command: black --skip-string-normalization --line-length=119 . --check --diff

--- examples/asr/jasper_eval.py	2020-04-08 15:41:06.829932 +0000

+++ examples/asr/jasper_eval.py	2020-04-08 15:41:42.539730 +0000

@@ -186,11 +186,11 @@

                     beta=beta,

                     lm_path=args.lm_path,

                     num_cpus=max(os.cpu_count(), 1),

                     input_tensor=False,

                 )

-                

+

                 beam_predictions = beam_search_with_lm(log_probs=logprobexp, log_probs_length=None, force_pt=True)

 

                 beam_predictions = [b[0][1] for b in beam_predictions[0]]

                 lm_wer = word_error_rate(hypotheses=beam_predictions, references=references)

                 logging.info("Beam WER {:.2f}%".format(lm_wer * 100))

would reformat examples/asr/jasper_eval.py

Oh no! 💥 💔 💥

1 file would be reformatted, 281 files would be left unchanged.

FAIL

script returned exit code 1
```

**Comment by dxdydz** [comment]
@okuchaiev Thanks for the tip. I did run that command, but it ended with an error (because black wasn't installed) that I didn't notice. Should be resolved now.

**Pull request merged**
