### PR TITLE
Remove redundant CLS and SEP in BERT pretraining dataset

### PR DESCRIPTION
**Pull request by qijiaxing**
As CLS and SEP are added when merging sentence a and b, there is no need to add them when reading each sentence from file.
Also, I removed the replacement of \xa0 by ' ', as \xa0 is part of a Chinese character utf8 encoding.

### CODE REVIEW

**Comment by okuchaiev** [comment]
@khcs can you please comment on this? Does it conflict with your PR (https://github.com/NVIDIA/NeMo/pull/58)?

**Comment by okuchaiev** [comment]
there are seem to be conflicts with master - could you please rebase

**Comment by qijiaxing** [comment]
> there are seem to be conflicts with master - could you please rebase

Rebased on latest master. Also fixed several small errors so that bert pretraining works now.

**Comment by qijiaxing** [comment]
As master has changed a lot, I will close this one and open a new one.

**Pull request closed without merging**
