### PR TITLE
Alit/mamba ux cicd

### PR DESCRIPTION
**Pull request by JRD971000**
# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by JRD971000** [comment]
@pablo-garay @ko3n1g This is the CICD for [MR10338](https://github.com/NVIDIA/NeMo/pull/10338) (SSMs migration to NeMo 2.0; already merged). I have a couple of questions/notes:

- Is the freeze already in place? If so could you point me to the release branch so adjust?
- The secret detector is a False positive I guess, and is not due to my changes

**Comment by ko3n1g** [comment]
> @pablo-garay @ko3n1g This is the CICD for [MR10338](https://github.com/NVIDIA/NeMo/pull/10338) (SSMs migration to NeMo 2.0; already merged). I have a couple of questions/notes:
> 
> * Is the freeze already in place? If so could you point me to the release branch so adjust?
> * The secret detector is a False positive I guess, and is not due to my changes

Hey @JRD971000 , yeah its `r2.0.0`. 

However starting this release we change the cherry-pick order, I was about to announce it. For a cherry-pick, you just need to add the label of the release branch (in this case: `r2.0.0`) to your PR (i just did that for you) and merge into main. Our automation will do the rest for you

**Comment by JRD971000** [comment]
> > @pablo-garay @ko3n1g This is the CICD for [MR10338](https://github.com/NVIDIA/NeMo/pull/10338) (SSMs migration to NeMo 2.0; already merged). I have a couple of questions/notes:
> > 
> > * Is the freeze already in place? If so could you point me to the release branch so adjust?
> > * The secret detector is a False positive I guess, and is not due to my changes
> 
> Hey @JRD971000 , yeah its `r2.0.0`.
> 
> However starting this release we change the cherry-pick order, I was about to announce it. For a cherry-pick, you just need to add the label of the release branch (in this case: `r2.0.0`) to your PR (i just did that for you) and merge into main. Our automation will do the rest for you

This is an awesome feature, thanks a lot Oliver!

**Comment by ko3n1g** [comment]
And regarding the secrets detector, @JRD971000 , yeah that's indeed weird. I will try to update the baseline again, it should definitely not flag your PR!

**Comment by JRD971000** [comment]
> And regarding the secrets detector, @JRD971000 , yeah that's indeed weird. I will try to update the baseline again, it should definitely not flag your PR!

Yeah it currently doesn't let me run CICD, all the tests skip due to this secret detector failure

**Comment by ko3n1g** [comment]
> > And regarding the secrets detector, @JRD971000 , yeah that's indeed weird. I will try to update the baseline again, it should definitely not flag your PR!
> 
> Yeah it currently doesn't let me run CICD, all the tests skip due to this secret detector failure

That actually sounds like a different problem that (also) shouldn't happen. We cancel pipelines/workflow runs automatically if a new commit is added. Maybe that's what happend here?

**Comment by ko3n1g** [comment]
After merging the updated secrets baseline into this branch, the secrets job passes. The main CICD workflow also runs, so I think we're ready set

**Comment by JRD971000** [comment]
> After merging the updated secrets baseline into this branch, the secrets job passes. The main CICD workflow also runs, so I think we're ready set

Awesome, thanks Oliver!

**Pull request merged**
