### PR TITLE
readme update - pip install

### PR DESCRIPTION
**Pull request by tkornuta-nvidia**
Changed the instructions on how one installs NeMo collections now

### CODE REVIEW

**Comment by blisc** [comment]
@okuchaiev, This would be a good argument as to why we would want a develop branch. I am against merging this PR because this would not be the correct instructions for r0.9 but rather the correct instructions for master branch.

**Comment by okuchaiev** [comment]
we have correct instructions for master - see "Installing from Github" section. @tkornuta-nvidia  please close

**Comment by tkornuta** [comment]
If I understood it correctly you are saying that those instructions are not correct NOW, but will be correct starting from the next release - and this is why we "reject" that PR?

@okuchaiev Will that PR be incorporated during the next release then? 

@blisc I think you are right - I guess people started to distinguish *master* from *develop*ment branch to deal with such cases on a "system level"... ;)

**Comment by tkornuta-nvidia** [comment]
Reopening that PR - is it is the right time now? ;)

**Pull request merged**
