### PR TITLE
Fix ASR issues

### PR DESCRIPTION
**Pull request by titu1994**
Signed-off-by: smajumdar <smajumdar@nvidia.com>

# What does this PR do ?
Bug fixes

**Collection**: [ASR]

# Changelog 
- Add specific line by line info of high level changes in this PR.

**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

### CODE REVIEW

**Review by nithinraok — COMMENTED** [review]
It should be 'gpu' . Cuda usage for accelarator is deprecated

**Comment by titu1994** [comment]
Hmm. Can you take the nvbug then ? Seems the test crashed with that.

**Comment by nithinraok** [comment]
Seems like cuda is not deprecated yet, tests are passing though. But on the src code it's not available, no idea what's happening. https://github.com/Lightning-AI/lightning/blob/dbb5ca8d436a917fc9c2bdd6e9c00e4fd6187735/src/pytorch_lightning/trainer/trainer.py#L196

**Comment by nithinraok** [comment]
It not the problem with code. You may close this, will be following up this on nvbug

**Pull request merged**
