### PR TITLE
Minor quantization pipeline updates

### PR DESCRIPTION
**Pull request by janekl**
# What does this PR do ?

Minor updates to quantization pipeline.

**Collection**: NLP

# Changelog 
- considering `megatron_amp_O2 = True` case
- fixing artifacts handling utils for a legacy .nemo checkpoint (for example, https://huggingface.co/nvidia/GPT-2B-001)

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by janekl** [comment]
jenkins

**Review by oyilmaz-nvidia — DISMISSED** [review]
LGTM.

**Comment by oyilmaz-nvidia** [comment]
jenkins

**Review by oyilmaz-nvidia — APPROVED** [review]
LGTM. We can merge once the CI passes.

**Pull request merged**
