### PR TITLE
update to unittesting

### PR DESCRIPTION
**Pull request by okuchaiev**
This PR adds "--with_downloads" argument for unittests.
```
# regular, GPU-based unit tests, without downloading pre-trained checkpoints from the clould
pytest
```
```
# regular, GPU-based unit tests including the ones which download pre-trained checkpoints from the clould
pytest --with_downloads
```

I also marked some tests which download checkpoints from the cloud with corresponding ```@pytest.mark.with_downloads()``` fixture.

### CODE REVIEW

**Review by titu1994 — COMMENTED** [review]
LGTM, but we should uncomment the megatron test before merge? Or is it intentional?

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Review by ericharper — CHANGES_REQUESTED** [review]
I just saw the export test is being skipped.

**Review by ericharper — APPROVED** [review]
get test is working, export is skipped (not working)

**Comment by okuchaiev** [comment]
> get test is working, export is skipped (not working)


- No, locally I get: tests/collections/nlp/test_megatron.py::TestMegatron::test_get_model FAILED  
E           RuntimeError: The following operation failed in the TorchScript interpreter.
E           Traceback of TorchScript (most recent call last):
E           RuntimeError: The following operation failed in the TorchScript interpreter.
E           Traceback of TorchScript (most recent call last):
E           RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

**Pull request merged**
