### PR TITLE
[DOC] move installation guide to doc intro from README

### PR DESCRIPTION
**Pull request by XuesongYang**
Signed-off-by: Xuesong Yang <1646669+XuesongYang@users.noreply.github.com>

# What does this PR do ?

This PR was cherry-picked from https://github.com/NVIDIA/NeMo/pull/5484, which attempted to merge r1.13.0. Rebased to r1.15.0.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by titu1994** [comment]
Why is all of this info being removed from the readme ? The readme is the first and main place for this info, the Nemo documentation page is secondary. Please revert these changes such that the readme is the most up to date and complete info, with the docs serving as further instructions or duplication of info

**Comment by XuesongYang** [comment]
> Why is all of this info being removed from the readme ? The readme is the first and main place for this info, the Nemo documentation page is secondary. Please revert these changes such that the readme is the most up to date and complete info, with the docs serving as further instructions or duplication of info

I swept @okuchaiev 's old PR that attempted to make such changes when working on r1.13.0. See this one: https://github.com/NVIDIA/NeMo/pull/5484

**Comment by titu1994** [comment]
How about we update the text to keep readme with the improved changes, and keep doc's as similar as possible ? Nemo devs look at readme first. We shouldn't have conflicting info in either docs or readme but removing from readme seems misguided

**Comment by SeanNaren** [comment]
Agree with @titu1994, happy with updating the "Key Features" section but I'd like the installs etc to stay in the README, since thats probably furthest where most people get.

**Pull request closed without merging**
