### PR TITLE
allow for labels with length > 1

### PR DESCRIPTION
**Pull request by dhpollack**
Currently, the audio dataset splits the transcript by character, which doesn't allow for labels which are greater than one character.  This makes it impossible to add labels such as `<NOISE>` or other special labels that one might want in the audio without some preprocessing hack such as replacing these labels with OOV single characters.  Nothing should change for normal label sets without special labels, but now special labels will get properly replaced with the appropriate token id.

Also, I refactored the naming a bit because I found it unintuitive that the input is a transcript of words and the output is a list of ints, but you were using the variable name `transcript` for both.

In the long run, a better solution would be to allow for a set of special tokens in the dataset; rather than adding them to the labels.  Currently, I also had to turn off the normalization so my tokens wouldn't get mangled because they contain punctuation.

Signed-off-by: David Pollack <david@i2x.ai>

### CODE REVIEW

**Comment by chiphuyen** [comment]
Thanks for your PR! It failed build because of a PEP8 style error:
```./collections/nemo_asr/nemo_asr/parts/manifest.py:143:80: E501 line too long (91 > 79 characters)```

Can you break the line to make it conform to PEP8? My suggestion:
```special_labels = set(
            [label for label in self.labels_map.keys() if len(label) > 1])
```

**Comment by dhpollack** [comment]
@blisc thanks for the quick review.  

>     * It would be nice if we don't have to disable normalize_string for this to work. It should be simple to loop through all characters present in labels_map and remove them from punctuation_to_replace that is passed to normalize_string. This is already done if you have a punctuation character in your labels, it should be simple to extend it to the case where your labels are not characters.

Currently, the normalization is an option in the yaml files, so it's easy to turn off.  For many of the normalization sub-functions, the whole transcript is an input.  I didn't look into refactoring all your code to make the normalization to work on the word level, but that is a much larger task than this PR.  Also, your suggestion of looping thru all characters would mean that you allow all characters in these special labels, such as `_`, `<`, or uppercase letters but it seems like you really only want these characters present in the specific cases where the full special label is present.

Also if you want to use this for anything other than English, you have to turn off the normalization.  For one, using `unidecode` removes all non-English characters such as ö, ä, é, è, which one would want to keep in other languages.  Not to mention common abbreviations replacements.  This mangles the labels in ways that one needs to dive into the source code to find.  There would either have to be a lot of rules for special labels such as forbidding uppercase, non-english characters, certain punctuation, etc because of normalization, or allowing people to use special characters but only if they turn off normalization.  I think anyone using special characters can preprocess their data to do exactly what the normalization does.  Overall, I think it's out of the scope of this PR to allow for special labels with normalization. 

>     * Do we want to split by space? The current design assumes that all special tokens are delimited by spaces. The case "he--she" is not currently handled. That seems like something that we might want to handle. We can add a space during normalize_string, or we can treat "<" as a special character such that all special tokens might be of the form "<ID_NAME>". Do you have any input as what would be preferred for your use case?

The case `"he--she"` would be handled if you put `he--she` as one of the labels, but I may be misintrepretting something.  The case that wouldn't be handled is if you wanted to have a space in your special label.  I think it's a better idea to not allow spaces in the labels.

As for splitting by space, I have made the assumption that all words are separated by a space and that special labels won't contain a space.  In general, I actually didn't like the idea of doing this because it does not generalize to languages that don't use spaces such as Chinese, but it would work exactly as it does now, so using this PR wouldn't make anything worse.  Also as stated earlier, the other normalizations are already very english-centric so anyone wanting to use this for a language that doesn't split words with spaces would need to write their own manifest loading classes or disable normalization.  I think the 

As for my motivation for this PR and a tangible example, is that I was using `<NOISE>` as one of the labels on a German dataset.  The normalization was turning `<NOISE>` to `noise` and `schön` to `schon`.

**Comment by dhpollack** [comment]
@chiphuyen, I can do that. I could also change "special_labels" to "sl" and/or "label" to "l" which would get It to 79 characters and limit to keep it all on on line.

**Comment by blisc** [comment]
> Overall, I think it's out of the scope of this PR to allow for special labels with normalization.

Thanks for your helpful insight regarding the current normalization scheme. It is something that we will look into past this PR.

> The case "he--she" would be handled if you put he--she as one of the labels, but I may be misintrepretting something. The case that wouldn't be handled is if you wanted to have a space in your special label. I think it's a better idea to not allow spaces in the labels.

I think I made a mistake while commenting. It should look like this `he--<SILENCE>--she`. I was wondering if you have any use cases that might be similar to this which might not work while delimiting with spaces. If not, let's merge the PR.

**Comment by dhpollack** [comment]
> I think I made a mistake while commenting. It should look like this `he--<SILENCE>--she`. I was wondering if you have any use cases that might be similar to this which might not work while delimiting with spaces. If not, let's merge the PR.

Ah, that makes more sense.  I believe if you want `he--<SILENCE>--she`, then you just put `he <SILENCE> she` in your transcript, so you separate all tokens with a space.  I can't think of why you'd want to add a token inside a word instead of splitting the token and the word/letters.  Something like `"what the heck"` should be in the transcript as `"what the <BEEP> K"` rather than `"what the <BEEP>K"`.  Even that seems like an extreme edge case.  Otherwise, I've never seen a token that was part of another word.

**Pull request merged**
