### PR TITLE
Fix PTL2.0 related ASR bugs in r1.21.0: Val metrics logging, None dataloader issue

### PR DESCRIPTION
**Pull request by KunalDhawan**
# What does this PR do ?

This PR added fixes for PTL2.0 related ASR bugs in r1.21.0: Val metrics logging, None dataloader issue

**Collection**: 
ASR, Core

# Changelog 
- val_dataloader() and test_dataloader() functions in nemo/core/classes/modelPT.py updated to handle cases where dataloader is None
- updated validation_pass(), validation_step(), test_step() in nemo/collections/asr/models/rnnt_models.py to correctly add metrics to validation_step_outputs, test_step_outputs. This is following the updates to ctc_models and hybrid_rnnt_ctc_models as done in [Upgrade to pytorch lightning 2.0](https://github.com/NVIDIA/NeMo/pull/6433/files#top)

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

### CODE REVIEW

**Review by nithinraok — APPROVED** [review]
LGTM

**Review by titu1994 — APPROVED** [review]
LGTM thanks!

**Review by stevehuang52 — APPROVED** [review]
LGTM ,thanks~~

**Review by athitten — APPROVED** [review]
LGTM, thank you for taking care of this @KunalDhawan!

**Pull request merged**
