### PR TITLE
Switch NeMo to safetensors with Compat mode

### PR DESCRIPTION
**Pull request by titu1994**
# What does this PR do ?

All checkpoints statedicts will be switched to safetensors following security recommendations against use of pkl (torch internally uses pickle format).

Additionaly, fix the model filter logic for HF based API search.

**Collection**: [Core]

# Changelog 
- Add the support of "ckpt_security_level" flag to SaveRestoreConnector
- Add compact and standard security modes
- In standard mode, only safetensor files can be read and written. If a legacy .ckpt checkpoint is attempted to be loaded into NeMos restoration engine, it will error out.
- In compat mode (the default), both pickle files and safetensors can be loaded for model restoration, however only safetensor files will be written to disk.
  - Compat mode is the default and will enable full backward compatibility with all older checkpoints.
  - It is the default mode (set as default inside the constructor). It must be explicitly updated to "standard" security mode that is stricter and breaks backward compatibility for .ckpt files.
- Fix a bug in an older test for Huggingface filters

# Usage
```python

from nemo.core.connectors.save_restore_connector import SaveRestoreConnector

connector = SaveRestoreConnector()
connector.ckpt_security_level = "standard"

# Will succeed if the checkpoint was saved with safetensors, fail if saved with .ckpt pickle file
model = ModelPT.restore_from("path/model.nemo", save_restore_connector=connector)
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

### CODE REVIEW

**Comment by titu1994** [comment]
jenkins

**Comment by titu1994** [comment]
jenkins

**Review by nithinraok — APPROVED** [review]
LGTM.

**Comment by titu1994** [comment]
jenkins

**Comment by titu1994** [comment]
jenkins

**Pull request closed without merging**
