### PR TITLE
Add dist ckpt support for regular optimizers

### PR DESCRIPTION
**Pull request by mikolajblaz**
# What does this PR do ?

Add dist checkpoint support for regular (non O2 and non-distributed) optimizers.
This change is required to support dist ckpt for FSDP training

**Collection**: NLP

# Changelog 
- Add dist checkpoint support for regular (non O2 and non-distributed) optimizers.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by mikolajblaz** [comment]
@erhoo82 do we still need this PR?

**Comment by dimapihtar** [comment]
jenkins

**Comment by dimapihtar** [comment]
jenkins

**Comment by dimapihtar** [comment]
jenkins

**Comment by dimapihtar** [comment]
jenkins

**Comment by pablo-garay** [comment]
LGTM. Thanks for merging this fix

**Pull request merged**
