### PR TITLE
Support Transcribing a Manifest File in `transcribe()` method

### PR DESCRIPTION
**Pull request by farisalasmary**
# What does this PR do ?

This PR enables transcribing an already existing manifest file instead of providing a list of audio files in the variable `paths2audio_files`.

**Collection**: ASR

# Changelog 
- Modified the `transcribe` method in the `EncDecCTCModel` class to support transcribing from manifest file. I first check that one of the arguments  `paths2audio_files` or `manifest_filepath` exists. If `manifest_filepath` is provided, add it to the `config` dict. Otherwise, create a temp manifest file from `paths2audio_files` list.

# Usage
* It can be combined with other models' output manifests, e.g. Lang ID, and use as an input to the ASR model using the `transcribe` method.

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [X] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by farisalasmary** [comment]
@titu1994

**Comment by titu1994** [comment]
The current design is intentional. We want the lowest level model function to receive pytorch tensors or file paths only. We'll be updating the API to tensors in the future 

However manifests, directories etc are not to be handled by the model code but by higher level scripts. We have transcribe speech for handling manifest and directories.

**Comment by farisalasmary** [comment]
This feature uses an already existing procedure that creates the temp manifest. This update enables providing your own manifest instead.

**Review by farisalasmary — COMMENTED** [review]
Updated the code format

**Comment by titu1994** [comment]
Yes I understand that, but we have script version of this already, and recommend using that for manifest handling. It supports many other cases, and all types of ASR models whereas this pr would need to be updated for each individual class that implements transcribe()

**Comment by farisalasmary** [comment]
Hi @titu1994,
I think this function already doing what's this pull request, can you confirm please?

https://github.com/NVIDIA/NeMo/blob/97f53ce2c4d236712650e701557c7872af104a32/nemo/collections/asr/parts/utils/transcribe_utils.py#L335

**Comment by titu1994** [comment]
Yes, and https://github.com/NVIDIA/NeMo/blob/main/examples/asr/transcribe_speech.py is the high level script to do inference on manifest

**Comment by farisalasmary** [comment]
thanks!! @titu1994
I think I should close this pull request as it is not needed anymore!

**Pull request closed without merging**
