### PR TITLE
Add support for replicated shard strategy for tarred datasets

### PR DESCRIPTION
**Pull request by titu1994**
# Changelog
- Support `replicate` strategy for sharding of tarfiles under ddp for Tarred WebDataset.
- Add config line to all ASR models

Signed-off-by: smajumdar <titu1994@gmail.com>

### CODE REVIEW

**Review by redoctopus — COMMENTED** [review]
General comment for configs: do we want to have `shard_strategy` set by default, when `is_tarred` is false by default?

**Comment by titu1994** [comment]
As in remove the configs shard_strategy = scatter portion? We could drop them, but it reduces visibility. Practically, it should be fine, since the shard strategy is not used unless is_tarred is set

**Comment by redoctopus** [comment]
I was worried about it potentially causing some confusion, since it's not explicitly named in relation to the tarred dataset. How do you feel about a `null` option like for `tarred_audio_filepaths` when `is_tarred` is False?

**Comment by titu1994** [comment]
Oh that's a good option. None by default switches to the current scatter strategy and otherwise the user sets it explicitly. I'll make the changes

**Comment by titu1994** [comment]
Another is to name the parameter `tarred_shard_strategy`

**Comment by redoctopus** [comment]
Either sounds good to me

**Review by redoctopus — APPROVED** [review]
LGTM

**Comment by titu1994** [comment]
Thanks !

**Pull request merged**
