### PR TITLE
refactor Manifest class and some optimizations

### PR DESCRIPTION
**Pull request by dhpollack**
Related to the previous PR, this allows one to create a 
more generic Manifest class.  Feel free to leave some comments 
if you disagree with any of the changes.  I also think some of 
these changes are technically "breaking" because I've changed 
the order of parameters and changed the names of the 
`Manifest` class.

This creates a more generic Manifest type and shows
how one can use this generic type to create a specialized
type, such as the one used for English ASR.

Secondly, the names of the variables was not consistent
with what the data actually represented.  Particularly,
the encoded tokens have changed names from `transcript` to
`tokens` to make it more clear that this is an encoded
representation of the text and not a text transcript.

Lastly, the code for the collate functions seemed relatively
inefficient and made a lot of assumptions regarding data types
and device.  There are changes which should work regardless
of the data types of the items in the batch.

Signed-off-by: David Pollack <david@i2x.ai>

### CODE REVIEW

**Comment by okuchaiev** [comment]
jenkins failed with PEP8 errors:

```
+ pycodestyle . --exclude=./scripts/get_librispeech_data.py,./scripts/process_beam_dump.py,./examples/nlp/end_of_sentence_tagging_with_bert.py,./examples/nlp/squad_with_pretrained_bert.py,./examples/nlp/transformer_translation.py,./tests/other/jasper.py,./tests/other/jasper_zero_dl.py,./collections/nemo_nlp/nemo_nlp/data/datasets/question_answering.py,./collections/nemo_nlp/nemo_nlp/data/datasets/token_classification.py,./collections/nemo_nlp/nemo_nlp/externals/bleu.py,./collections/nemo_nlp/nemo_nlp/externals/fairseq_tokenizer.py,./collections/nemo_nlp/nemo_nlp/externals/file_utils.py,./collections/nemo_nlp/nemo_nlp/externals/run_squad.py,./collections/nemo_nlp/nemo_nlp/externals/sacrebleu.py,./collections/nemo_nlp/nemo_nlp/externals/tokenization.py,./nemo/setup.py,./docs/sources/source/conf.py,./docs/sources/source/tutorials/infer.py,./docs/sources/source/tutorials/test.py,./collections/nemo_nlp/build

./collections/nemo_asr/nemo_asr/parts/dataset.py:122:80: E501 line too long (80 > 79 characters)

./collections/nemo_asr/nemo_asr/parts/dataset.py:123:80: E501 line too long (80 > 79 characters)

./collections/nemo_asr/nemo_asr/parts/manifest.py:91:80: E501 line too long (81 > 79 characters)

./collections/nemo_asr/nemo_asr/parts/perturb.py:98:80: E501 line too long (83 > 79 characters)

script returned exit code 1
```

**Comment by dhpollack** [comment]
@okuchaiev I can make the changes, but have you considered allowing for longer line lengths such as 99 characters or 119 characters?  I find the 79 character limit a little restricting as I basically end up using less descriptive variable names to get under the limit.  I even created a generator method (`json_item_gen`) whose sole purpose is to save 12 characters per line.  I don't mind sticking to 79 characters, but I wanted to put in my 2 cents in case this was something that was up for debate.

**Comment by okuchaiev** [comment]
@dhpollack we chose to follow PEP8 because it is a well-known external code style guide that is easily enforced and checked by popular IDEs and tools.
While 79 character limit per line can indeed look to short be when viewing a single file, in practice, people frequently have more than one open, it also helps to review changes.
Rest of the code-base follows PEP8 (with, perhaps, minor exceptions which should be fixed), thus, let's please stick to PEP8

**Comment by okuchaiev** [comment]
@dhpollack in this PR you are changing "Manifest" class into "ManifestEN" and "ManifestBase". 
It seems to me that this is justified if:
1) There will be "ManifestNon-En" class, right? If yes do you plan to add one and for what language?
2) AudioDataset class should then have an ability to specify which manifest class to utilize (with default to ManifestEN)

**Comment by dhpollack** [comment]
@okuchaiev sorry, I went on vacation, so I took a step away from my computer for a bit.  I made the linting changes and I agree with your idea about being able to select a manifest class in the `AudioDataset`, so I added that.

As for a non-english example, my use case is German.  But I think that I could either use the ManifestBase with normalization turned off or ManifestEN with normalization turned off.  I don't necessarily think another language needs to be included with the library, but I do think that it should be obvious that the current default is specifically for English.  I also think that it signals to users of the library that if they want to use this for a non-English language that they will probably have to write their own processor for the text portion.

**Comment by okuchaiev** [comment]
@dhpollack I looked through your PR and it looks good to me. Also, regarding this: " I don't necessarily think another language needs to be included with the library" - I think it is great to include other language support with the library. Please also see this issue: https://github.com/NVIDIA/NeMo/issues/71 - It looks like they could add something like ManifestCN with their own normalization. Feel free to add ManifestDE if you feel like it is helpful.

Regarding this PR - is it still WIP?

**Comment by dhpollack** [comment]
@okuchaiev I removed the WIP.

I guess what I mean is that I don't necessarily have a specific public dataset for German that I can add at this time.  Right now I just add the German characters that I need to the labels and then turn off normalization.  I'll look at some other examples of German datasets such as [one used by these guys](https://github.com/uhh-lt/kaldi-tuda-de) and look into building a proper German manifest for the future.

**Pull request merged**
