### PR TITLE
Apex/Megatron dependencies fix

### PR DESCRIPTION
**Pull request by tkornuta-nvidia**
This PR focuses on fixing the dependency issue in NeMo:
 * NeMo **optionally** depends on Apex
 * NeMo NLP collection depends on megatron-lm
 * megatron-lm **requires** on Apex
As a result, our `./reinstall/setup.py` might install `megatron`, but without Apex the code will crush. And not one examle - ALL CODE/EXAMPLES/TESTS

Fix:
 * [x] try around megatron-related imports
 * [x] __megatron_..._satisfied flag that is used for injecting megatron-dependent code artifacts

Additionally it cleans up several files from unnecessary importing whole NeMo (`import nemo`):
 * [x] replaces all `logging = nemo.logging` with from `nemo.utils import logging`
 * [x] removes all unused `import nemo'

### CODE REVIEW

**Comment by blisc** [comment]
What is the fix? And why are you changing in to nemo.utils.logging?

**Comment by tkornuta-nvidia** [comment]
Hey, @blisc just described that in the PR description

**Comment by blisc** [comment]
> Hey, @blisc just described that in the PR description.
> 
> But in short: `logging = nemo.logging` required to call `import nemo` apriori.
> 
> 1. I think it is an unnecessary burden to load the whole package just to get access to the logger
> 2. LGTM was complaining and throwing warnings about each `from nemo.xxx import yyy` called after `import nemo` (something in the spirit of: `Using both "import" and "from" when using the package nemo`)
> 
> Hope it helps.

This makes sense if there is a file that only imports the logger but not nemo. But that doesn't seem to happen often. So I don't why we are doing this.

As for the LGTM error, if you look at their recommended solution, it is just to do
```
import nemo
logging = nemo.logging
```

**Comment by tkornuta-nvidia** [comment]
> > Hey, @blisc just described that in the PR description.
> > But in short: `logging = nemo.logging` required to call `import nemo` apriori.
> > 
> > 1. I think it is an unnecessary burden to load the whole package just to get access to the logger
> > 2. LGTM was complaining and throwing warnings about each `from nemo.xxx import yyy` called after `import nemo` (something in the spirit of: `Using both "import" and "from" when using the package nemo`)
> > 
> > Hope it helps.
> 
> This makes sense if there is a file that only imports the logger but not nemo. But that doesn't seem to happen often. So I don't why we are doing this.
> 
> As for the LGTM error, if you look at their recommended solution, it is just to do
> 
> ```
> import nemo
> logging = nemo.logging
> ```
> 
> As from this link: https://lgtm.com/rules/1818040193/

You are correct. But please note then a) xxx = main nemo package and b) in many cases we were importing **not only logging**.

That resulted in mixed cases like:
```
import nemo
logging = nemo.logging
from nemo.core import bla1, bla2, bla3
```
which still conveyed *the same type of error*

**Comment by blisc** [comment]
> > > Hey, @blisc just described that in the PR description.
> > > But in short: `logging = nemo.logging` required to call `import nemo` apriori.
> > > 
> > > 1. I think it is an unnecessary burden to load the whole package just to get access to the logger
> > > 2. LGTM was complaining and throwing warnings about each `from nemo.xxx import yyy` called after `import nemo` (something in the spirit of: `Using both "import" and "from" when using the package nemo`)
> > > 
> > > Hope it helps.
> > 
> > 
> > This makes sense if there is a file that only imports the logger but not nemo. But that doesn't seem to happen often. So I don't why we are doing this.
> > As for the LGTM error, if you look at their recommended solution, it is just to do
> > ```
> > import nemo
> > logging = nemo.logging
> > ```
> > 
> > 
> > As from this link: https://lgtm.com/rules/1818040193/
> 
> You are correct. But please note the mentioned a) xxx in here is the main nemo package and b) in many cases we were importing from the nemo package **not only logging**.
> 
> That resulted in mixed cases like:
> 
> ```
> import nemo
> logging = nemo.logging
> from nemo.core import bla1, bla2, bla3
> ```
> 
> which still conveyed _the same type of error_

Can we keep what we had before inside of examples and the tutorial rst files?
But let's keep this change for files under the nemo folder.

**Comment by tkornuta-nvidia** [comment]
> Can we keep what we had before inside of examples and the tutorial rst files?
> But let's keep this change for files under the nemo folder.

It really makes no sense to me. Please think about it. In **every** NeMo application you simply **must import something more from nemo package** aside of nemo.logging. Maybe something from nemo.core (e.g. NeuralModuleFactory)? Or a callback? Or an action? Or a module from nemo.collections etc.? 

**So why to present to the user even one example that will enable him/her to produce this code with an error at all**?

What is your point here?

**Comment by blisc** [comment]
> > Can we keep what we had before inside of examples and the tutorial rst files?
> > But let's keep this change for files under the nemo folder.
> 
> It really makes no sense to me. Please think about it. In **every** NeMo application you simply **must import something more from nemo package** aside of nemo.logging. Maybe something from nemo.core (e.g. NeuralModuleFactory)? Or a callback? Or an action? Or a module from nemo.collections etc.?
> 
> **So why to present to the user even one example that will enable him/her to produce this code with an error at all**?
> 
> What is your point here?

Can we stop changing recommended API? I want to have a consistent style across is the codebase.
Regarding LGTM errors, I see no fixed LGTM errors in your PR. Thus I don't understand why this is an issue. The code pattern of 
```
import nemo
logging = nemo.logging
from nemo.core import bla1, bla2, bla3
```
raises no LGTM errors.

**Comment by blisc** [comment]
> > > Can we keep what we had before inside of examples and the tutorial rst files?
> > > But let's keep this change for files under the nemo folder.
> > 
> > 
> > It really makes no sense to me. Please think about it. In **every** NeMo application you simply **must import something more from nemo package** aside of nemo.logging. Maybe something from nemo.core (e.g. NeuralModuleFactory)? Or a callback? Or an action? Or a module from nemo.collections etc.?
> > **So why to present to the user even one example that will enable him/her to produce this code with an error at all**?
> > What is your point here?
> 
> Can we stop changing the recommended API? I want to have a consistent style across the codebase.
> Regarding LGTM errors, I see no fixed LGTM errors in your PR. Thus I don't understand why this is an issue. The code pattern of
> 
> ```
> import nemo
> logging = nemo.logging
> from nemo.core import bla1, bla2, bla3
> ```
> 
> raises no LGTM errors.

Discussed this offline, we noted the concerns and advantages and will move forward with this change to `from nemo.utils import logging`.

**Pull request merged**
