### PR TITLE
Wav2vec fix

### PR DESCRIPTION
**Pull request by bonham79**
# What does this PR do ?

Fixes Wav2Vec configs so compatible with contrastive loss. (Adds MaskedAugmentation to pretrain models.) Removes Wav2Vec from experimental folder and moves wav2vec configs to SSL folder for consistency.

**Collection**: [Note which collection this PR will affect]

- ASR

# Changelog 
- Wav2Vec Pretrain (Base and Large): replaces SpecAug with MaskedPatchAugmentation. Adds appropriate contrastive loss flags.
- Deleted Wav2Vec folder from `examples/experimental`
- Moved Wav2Vec configs to `conf/SSL`

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ Y] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ N] Did you write any new necessary tests?
- [ N] Did you add or update any necessary documentation?
- [ N] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [Y ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by bonham79** [comment]
@sam1373 Mind giving an eye over of the configs? Just tweaked what's used in the SSL configs.

**Review by sam1373 — APPROVED** [review]
looks good, maybe add a test for it

**Comment by sam1373** [comment]
actually wav2vec ctc configs shouldn't be in ssl

**Comment by bonham79** [comment]
> actually wav2vec ctc configs shouldn't be in ssl

So guess we should keep a wav2vec folder? In that case, wouldn't it just confuse people for the pretrain not to be there?

**Comment by sam1373** [comment]
> So guess we should keep a wav2vec folder? In that case, wouldn't it just confuse people for the pretrain not to be there?

Well that is what we currently do for other models

**Comment by bonham79** [comment]
> Well that is what we currently do for other models

Fair enough, ill just make wav2vec_ctc folder.

**Comment by bonham79** [comment]
@sam1373 Jenkins approved.

**Review by sam1373 — APPROVED** [review]

**Pull request merged**
