### PR TITLE
Add nemo2 conversion scripts for export

### PR DESCRIPTION
**Pull request by meatybobby**
# What does this PR do ?

Add nemo2 conversion scripts for export

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ericharper** [comment]
Let's add some docs and ci test then we can merge.

**Comment by marcromeyn** [comment]
If possible we'd like to keep the number of scripts to a minimum and instead add things like this to our CLI. You can look at [api.py](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/api.py) as examples for things like train, finetune, etc. We have some docs around creating CLI-entrypoints [here](https://github.com/NVIDIA/NeMo-Run/tree/main/examples/entrypoint).

**Comment by meatybobby** [comment]
This is a temporary solution for exporting nemo2 ckpt. Eventually we will integrate this into megatron, so we won't add this into api.

**Comment by meatybobby** [comment]
This script has been tested by llama3-8b nemo2 checkpoint.

**Review by akoumpa — APPROVED** [review]
I'm approving on the basis this is temporary solution to unblock things.

**Pull request merged**
