### PR TITLE
Add new text segmentation library for better TTS quality

### PR DESCRIPTION
**Pull request by RobinDong**
# What does this PR do ?
When running below snippet for using FastPitch model trained from AISHELL-3 (the `aishell3.nemo` is from [here](https://github.com/RobinDong/nemo_models/blob/main/models/aishell3.nemo))
```python
from nemo.collections.tts.models import FastPitchModel
from nemo.collections.tts.models import HifiGanModel

spec_generator = FastPitchModel.restore_from("~/aishell3.nemo")
model = HifiGanModel.from_pretrained(model_name="tts_zh_hifigan_sfspeech")

# Generate audio
import soundfile as sf
import torch
with torch.no_grad():
    parsed = spec_generator.parse("这些新一代的中央处理器不只效能惊人。")
    spectrogram = spec_generator.generate_spectrogram(tokens=parsed, speaker=1)
    audio = model.convert_spectrogram_to_audio(spec=spectrogram)
    if isinstance(audio, torch.Tensor):
        audio = audio.to('cpu').numpy()

# Save the audio to disk in a file called speech.wav
sf.write("speech.wav", audio.T, 22050, format='WAV')
```
The `jieba` will segment the input text to
```python
['这些', '新一代', '的', '中央处理器', '不', '只', '效能', '惊人', '。']
```
and the phoneme for '只' is "zhi1", which is incorrect in this context.

But using `pkuseg`, the input text will be segmented to
```python
['这些', '新一代', '的', '中央', '处理器', '不只', '效能', '惊人', '。']
```
and the phonemes for '只' is "zhi3", which is correct.

# Changelog 
- Add a new text-segmentation-library to make better TTS quality for the Chinese language

# Usage
Setting `word_segmenter` from `jieba` to `pkuseg` in the configuration file `fastpitch_config.yaml`: 
```python
...
spec_generator = FastPitchModel.restore_from("~/aishell3.nemo", override_config_path="fastpitch_config.yaml")
...
```
The TTS sample that use `jieba`: [before.zip](https://github.com/NVIDIA/NeMo/files/12817139/before.zip)
The TTS sample that use `pkuseg`: [after.zip](https://github.com/NVIDIA/NeMo/files/12817141/after.zip)

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [x] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [x] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

## Who can review?

@XuesongYang @blisc

### CODE REVIEW

**Comment by XuesongYang** [comment]
Thanks. pkuseg is a great segmenter for sure, but I remembered pkuseg brings larger computation overhead than jieba. This paper proposed an even better model: https://aclanthology.org/2022.acl-long.13.pdf.

**Comment by RobinDong** [comment]
> Thanks. pkuseg is a great segmenter for sure, but I remembered pkuseg brings larger computation overhead than jieba. This paper proposed an even better model: https://aclanthology.org/2022.acl-long.13.pdf.

Interesting paper. Does it have a handy library of Python?

**Comment by XuesongYang** [comment]
Made some changes. What do you think?

**Comment by RobinDong** [comment]
> Made some changes. What do you think?

Looks good to me. 
Thanks!

**Review by XuesongYang — APPROVED** [review]

**Pull request merged**
