### PR TITLE
Jiaqiz/option to disable adapters & merge all lora layers

### PR DESCRIPTION
**Pull request by HeyyyyyyG**
# What does this PR do ?

Add a condition for all adapters modules: run through the adapter only when it is enabled

Add merging script for all lora layers.

# Usage
To enable or disable an adapter, we can use

```python
AdapterModuleMixin.set_enabled_adapters(name, enabled = True)
AdapterModuleMixin.set_enabled_adapters(name, enabled = False)
```
If ```name``` is not provided, then all adapters will be enabled/disabled. For example, one can disable all adapters using the following codes, which is equivalent to use only the base model.
```python
from nemo.core.classes.mixins.adapter_mixins import AdapterModuleMixin
for _, module in model.named_modules():
    if isinstance(module, AdapterModuleMixin) and module.is_adapter_available():
        module.set_enabled_adapters(enabled=False)
```

**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by arendu** [comment]
@HeyyyyyyG is this WIP?

**Review by cuichenx — DISMISSED** [review]
LGTM! but i think we should merge #7988 before this one

**Comment by HeyyyyyyG** [comment]
> LGTM! but i think we should merge #7988 before this one

Yes totally agree

**Comment by HeyyyyyyG** [comment]
jenkins

**Comment by HeyyyyyyG** [comment]
jenkins

**Comment by HeyyyyyyG** [comment]
jenkins

**Comment by HeyyyyyyG** [comment]
jenkins

**Review by cuichenx — APPROVED** [review]
LGTM

**Pull request merged**
