### PR TITLE
Mean normalization

### PR DESCRIPTION
**Pull request by nithinraok**
fix voxceleb eval and add embedding normalization

### CODE REVIEW

**Review by jbalam-nv — APPROVED** [review]
LGTM

**Review by titu1994 — COMMENTED** [review]
Mean normalization over batch dim? Wont this make it dependent on what batch of samples you get at any time ?

**Comment by nithinraok** [comment]
> Mean normalization over batch dim? Wont this make it dependent on what batch of samples you get at any time ?

yes, this is normalization over batch samples. This is to minimize the source channel effect on embeddings before we compute cosine distance score on enrolled speaker and impostor speaker (verification). There is another normalization called global which doesn't depend on batch dim. Will add that once ready, fully tested, and ready for diarization cases.

**Review by titu1994 — APPROVED** [review]
Ok sounds good then. Maybe docs need to be updated later

**Pull request merged**
