### PR TITLE
Pass in rotary_base to mcore and from HF

### PR DESCRIPTION
**Pull request by Kipok**
# What does this PR do ?

This depends on the following mcore commit https://github.com/NVIDIA/Megatron-LM/commit/d931ba8a492801d9d74efba6be94f82387090e57, so if it's not yet integrated into our main branch, we'd need to wait before merging this PR.

**Collection**: NLP
# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by ericharper** [comment]
jenkins

**Comment by ericharper** [comment]
jenkins

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Comment by tdene** [comment]
This PR incremented the version of Megatron Core from `e122536b7645edcb7ebf099b5c92a443f7dbf8e7` to `973330e9c3681604703bf1eb6b5a265d1b9b9b38`, that is from 0.3.0 to 0.4.0, but did not change the [requirements file](https://github.com/NVIDIA/NeMo/blob/main/requirements/requirements_nlp.txt#L13) accordingly

**Pull request merged**
