### PR TITLE
Update TTS notebook with TalkNet inference

### PR DESCRIPTION
**Pull request by stasbel**
Signed-off-by: Stanislav Beliaev <stasbelyaev96@gmail.com>

### CODE REVIEW

**Comment by blisc** [comment]
Can you send this to v1.0.0 instead?

**Comment by stasbel** [comment]
@blisc ready for review

**Review by Oktai15 — CHANGES_REQUESTED** [review]
Nice job!

`3_TTS_TalkNet_Training.ipynb` has three unsolved TODO's:

First cell: `TODO: change branch to release?`
Need discuss it with @blisc 

Text in `Introduction` section: `TODO: update link to new version of paper?`
@stasbel, please, update link to new TalkNet 2 paper: https://arxiv.org/abs/2104.08189

Sixth cell: `TODO: change branch to release?`
Need discuss it with @blisc

**Comment by stasbel** [comment]
link is fixed
branch choice is yet to be commented by @blisc

**Comment by blisc** [comment]
> link is fixed
> branch choice is yet to be commented by @blisc

Please use `v1.0.0` for all files and branches

**Review by Oktai15 — APPROVED** [review]
LGTM

**Pull request merged**
