### PR TITLE
[TTS] Fix audio codec type checks

### PR DESCRIPTION
**Pull request by rlangman**
# What does this PR do ?

Most classes in the audio codec code had input_type() and output_type() parameters but were missing the typecheck() annotation on the forward() method to enforce them.

This commit adds the typecheck() to all relevant forward() methods and fixes their corresponding type annotations.

Also has a small change to add the vector quantizer parameters to the optimizer in the model (though the existing RVQ has no trainable parameters).

**Collection**: [TTS]

# Changelog 
- Add typecheck to forward methods
- Fix various typos in input/output types

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

### CODE REVIEW

**Review by nithinraok — DISMISSED** [review]
LGTM

**Comment by nithinraok** [comment]
Are they no test cases for Codecs yet?

**Comment by rlangman** [comment]
> Are they no test cases for Codecs yet?

There are only a few. We haven't added CI tests which run the recipe itself, and I could not think of many tests that were not effectively just asserting what the neural typechecking is supposed to validate automatically at runtime in terms of types/dimensions of each module (though clearly it wasn't being validated).

**Comment by titu1994** [comment]
Type checks work if the entire pipeline of types is setup - including data loader and loss.

**Pull request merged**
