### PR TITLE
add pleasefixme marker for potential failed nightly tests.

### PR DESCRIPTION
**Pull request by XuesongYang**
# What does this PR do ?

Associated to https://github.com/NVIDIA/NeMo/pull/7627. Add pleasefixme marker as an temporal solution.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by blisc** [comment]
Are these tests failing? I don't see any failures on the latest commit on main

**Comment by XuesongYang** [comment]
> Are these tests failing? I don't see any failures on the latest commit on main

This test is not captured in our CI. Instead, I developed a nightly test. If you run `pytest --nightly tests/collections/tts/models`, you should see 
```
FAILED tests/collections/tts/models/test_fastpitch.py::test_inference[tts_zh_fastpitch_sfspeech] - AssertionError: Syllable <> does not exist in the dictionary.

```

**Review by titu1994 — APPROVED** [review]
Seems reasonable, thanks

**Comment by XuesongYang** [comment]
@blisc do you have any other comments?

**Comment by blisc** [comment]
Feel free to merge. But I do question the use of a test that isn't being run.

**Comment by XuesongYang** [comment]
> Feel free to merge. But I do question the use of a test that isn't being run.

Agreed. I forgot to mention that our QA runs `pytest --nightly tests/collections/tts/models` internally for every release.

**Pull request merged**
