### PR TITLE
modelopt=0.21.0 update

### PR DESCRIPTION
**Pull request by janekl**
# What does this PR do ?

* ~~Bugfix to correctly support Mixtral for PTQ in NeMo 2.0.~~ done in https://github.com/NVIDIA/NeMo/pull/11607
* Updating `nvidia-modelopt=0.21.0`

**Collection**: LLM / NLP

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to https://github.com/NVIDIA/NeMo/pull/11607

### CODE REVIEW

**Review by Laplasjan107 — APPROVED** [review]

**Review by kevalmorabia97 — APPROVED** [review]

**Review by ko3n1g — CHANGES_REQUESTED** [review]
Why is modelopt not part of requirements txt?

**Comment by janekl** [comment]
> Why is modelopt not part of requirements txt?

I think Eric wanted it to be only an optional requirement for NeMo in the initial integration effort (see [here](https://github.com/NVIDIA/NeMo/pull/8444#discussion_r1514770391) and [here](https://github.com/NVIDIA/NeMo/pull/8444/commits/ae88e4744e43f0c7afc7d6bc8739a42a05a18209#r1514771010)). It's also import guarded (see [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/quantization/quantizer.py#L34-L51), for example).

Are you suggesting to revisit this decision?

**Comment by ko3n1g** [comment]
> > Why is modelopt not part of requirements txt?
> 
> I think Eric wanted it to be only an optional requirement for NeMo in the initial integration effort (see [here](https://github.com/NVIDIA/NeMo/pull/8444#discussion_r1514770391) and [here](https://github.com/NVIDIA/NeMo/pull/8444/commits/ae88e4744e43f0c7afc7d6bc8739a42a05a18209#r1514771010)). It's also import guarded (see [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/quantization/quantizer.py#L34-L51), for example).
> 
> Are you suggesting to revisit this decision?

If this was for initial implementation then yes, let’s revisit it. But not necessarily as part of this PR. Thanks for explaining!

**Review by ko3n1g — APPROVED** [review]

**Comment by janekl** [comment]
This needs to be synced with an update on container side, I'll let you know once ready

**Pull request merged**
