### PR TITLE
Update CMUdict with more recent 0.7b entries

### PR DESCRIPTION
**Pull request by redoctopus**
Signed-off-by: Jocelyn Huang <jocelynh@nvidia.com>

# What does this PR do ?

Merges the existing NeMo CMUdict with a version of 0.7b with added entries.

**Collection**: TTS

# Changelog 
- Added entries from https://github.com/Alexir/CMUdict/blob/master/cmudict-0.7b
- I've omitted entries with British spellings

### CODE REVIEW

**Comment by XuesongYang** [comment]
May I know how to tell British spelling for a word in the dict? Are there some rules you are applying to achieve this?

**Comment by redoctopus** [comment]
> May I know how to tell British spelling for a word in the dict? Are there some rules you are applying to achieve this?

Standard US and British English have different spellings for some words, so I've left out e.g. "DEMEANOUR" (vs. the US English "DEMEANOR" which is already in the dictionary), "MODELLING" ("MODELING" in the US), etc. I'm not aware of any particular rules of thumb here.

**Comment by XuesongYang** [comment]
> > May I know how to tell British spelling for a word in the dict? Are there some rules you are applying to achieve this?
> 
> Standard US and British English have different spellings for some words, so I've left out e.g. "DEMEANOUR" (vs. the US English "DEMEANOR" which is already in the dictionary), "MODELLING" ("MODELING" in the US), etc. I'm not aware of any particular rules of thumb here.

Thanks for the detailed info! Removing British spellings indicates all those spellings are considered as OOV so that G2P or graphemes would be triggered. If this is the case we've already reviewed, then we could proceed. 

@blisc could you please share your thoughts here?

**Comment by blisc** [comment]
Can you increment to 22.08.1?

**Review by XuesongYang — APPROVED** [review]
Synced with @blisc offline. We are good to go. Thanks!

**Pull request merged**
