### PR TITLE
Fix export of configuration parameters to Weights and Biases

### PR DESCRIPTION
**Pull request by soluwalana**
# What does this PR do ?

This PR corrects an error in ModelPT.py that only partially converts the _hparams_initial from an OmegaConf object to a dictionary before exporting to the various loggers. 

This was particularly an issue with search functionality based on metadata in Weights and Biases due to the cfg object being a string representation of the OmegaConf object.

**Collection**: Core

# Changelog 
- Adds an additional check and conversion of the OmegaConf self._cfg to ensure that Logger.log_hyperparameters from Pytorch Lightning is guaranteed to find a JSON compatible structure at L1650 of core/classes/ModelPT.py

### Prior to fix

cfg is recorded as a str(OmegaConf.DictConfig) in Weights and Biases 

Screenshot 2024-10-22 at 11 21 02

### After fix

cfg is correctly searchable in Weights and Biases

Screenshot 2024-10-22 at 11 21 17

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue) LLM-5007

### CODE REVIEW

**Review by titu1994 — APPROVED** [review]
Makes sense, thanks for the fix !

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Comment by soluwalana** [comment]
@ericharper @titu1994 can you trigger the Nemo_CICD_Test, cicd-test-container-setup, and gpu-test actions?

**Review by ericharper — APPROVED** [review]
LGTM. Thanks!

**Review by titu1994 — APPROVED** [review]
Thanks !

**Pull request merged**
