### PR TITLE
Unify HF converter scripts and arguments

### PR DESCRIPTION
**Pull request by yaoyu-33**
# What does this PR do ?

Unify HF converter scripts and arguments

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by yaoyu-33** [comment]
jenkins

**Comment by yaoyu-33** [comment]
jenkins

**Comment by yaoyu-33** [comment]
jenkins

**Comment by yaoyu-33** [comment]
jenkins

**Comment by yaoyu-33** [comment]
jenkins

**Comment by yaoyu-33** [comment]
jenkins

**Comment by janekl** [comment]
Looks good, these scripts look much better now. Some minor remarks:
* I often do CTRL+F on some arguments like, for example, `in_file`. For the current style like `parser.add_argument("--in-file", ...)` -- dash vs underscore -- such searches won't work for argument definitions which is sometimes inconvenient.
* For StarCoder I think we have [a standalone config](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/conf/megatron_starcoder_config.yaml) now so can we change default for `--hparams-file` to that? Maybe @dimapihtar could additionally confirm
* Maybe we can drop size param = `7b` for Mistral conversion files to further unify names? This one comes only in one flavor anyway
* I would pass all arguments to `load_config` explicitely rather than with `args` unless it's really inconvenient / inflexible (but it's up to you)
* In some cases we could use `load_state_dict_helper` or `torch_dtype_from_precision` util functions from nemo/collections/nlp/parts/utils_funcs.py

**Comment by yaoyu-33** [comment]
@janekl  Thanks for the comments.
I changed 1 - dash to underscore
For the rest, I don't have BW to change and verify all atm. We can proceed to ask the original PICs to update them in the following PR.

**Comment by yaoyu-33** [comment]
jenkins

**Pull request closed without merging**
