### PR TITLE
Make onnx-graphsurgery an optional deferred import

### PR DESCRIPTION
**Pull request by titu1994**
# Changelog
- onnx-graphsurgery is not available on all platforms, and breaks pip install (currently tested on darwin and some versions of ubuntu).
- Make it an optional import that performs runtime check instead.

### CODE REVIEW

**Comment by tkornuta-nvidia** [comment]
Hmmm, I think the line that was breaking NeMo installation on my MacBook was in `setup.py`:
https://github.com/NVIDIA/NeMo/blob/45f60f03e5d15a4b6e7db145b5d731d73f3a891d/setup.py#L235

@borisfom ideas?

**Review by okuchaiev — APPROVED** [review]
lgtm

**Comment by okuchaiev** [comment]
> Hmmm, I think the line that was breaking NeMo installation on my MacBook was in `setup.py`:
> https://github.com/NVIDIA/NeMo/blob/45f60f03e5d15a4b6e7db145b5d731d73f3a891d/setup.py#L235
> 
> @borisfom ideas?

@tkornuta-nvidia Doesn't seem like this PR breaks MacOS compatibility. It looks like it was broken before? This PR change reduces ```setup_requires=['pytest-runner', 'nvidia-pyindex'],``` to ```setup_requires=['pytest-runner']```

**Review by tkornuta-nvidia — APPROVED** [review]

**Comment by titu1994** [comment]
Awaiting @borisfom review before merge

**Comment by titu1994** [comment]
Merged as main branch is broken without this, preventing other prs

**Comment by borisfom** [comment]
Sorry to be late for the game - I am on vacation right now ...
Too bad onnx-graphsurgeon is not available on all platforms - we would need to think how to handle those cases properly in general. It makes it rather difficult  to have seamless setup.py, without hairy scripts around. As my original change was primarily to enable a workaround for TRT issue that will hopefiully be fixed, it's probably fine in this case. 
The way it's left after this PR merged is not right though: 
1. constant_folding argument is defunct (always overridden). We should revert changes to it and only have onnx-graphsurgeon invocation under the GRAPGSURGEION_AVAILABLE conditional.
2. default setup.py would not install onnx-graphsurgeon on any platform. That's probably the best we can do at the moment and have developers who need to use this WAR, to install it manually - but we should think of general way of handling optional components to have best experience on all platforms. It sees that, besides WAR for TRT 'double' issue, onnx-graphsurgeon pass makes most of the graphs more compact (potentially faster, one needs to check), so it would probably be nice to keep it enabled for the platforms that have it, even when TRT issue is fixed.

**Pull request merged**
