### PR TITLE
Handle class balancing in a way to support TLT.

### PR DESCRIPTION
**Pull request by VahidooX**

### CODE REVIEW

**Review by tkornuta-nvidia — APPROVED** [review]
Generally looks good to me.

1) I would indicate in PR description that it also adds Export.
2) Please consider covering class balancing in CI

**Review by okuchaiev — APPROVED** [review]
lgtm, thx

**Review by okuchaiev — CHANGES_REQUESTED** [review]
@borisfom  can you please have a look? I think we had issues with attach_onnx_to_onnx

**Review by borisfom — CHANGES_REQUESTED** [review]
Please rebase to latest main - export() and attach_onnx_to_onnx should disappear.

**Comment by VahidooX** [comment]
> 
> 
> Please rebase to latest main - export() and attach_onnx_to_onnx should disappear.

Dropped them.

**Review by okuchaiev — APPROVED** [review]

**Pull request merged**
