### PR TITLE
Temporary pin Lightning-Utilities version due to broken NamedTuple

### PR DESCRIPTION
**Pull request by artbataev**
# What does this PR do ?

Pin Lightning-Utitilies package version due to broken NamedTuple in `0.10.0`
https://github.com/Lightning-AI/utilities/pull/160 introduced the issue, 
https://github.com/Lightning-AI/utilities/blob/a00e1144dd300e3bc2fc8746a8e85510ffe35aa7/src/lightning_utilities/core/apply_func.py#L67 here NamedTuple force converted to tuple.

This fixes the bug https://nvbugspro.nvidia.com/bug/4405798 (broken `ASR_TTS_Tutorial`)

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by titu1994** [comment]
jenkins

**Review by titu1994 — APPROVED** [review]
Fyi @athitten @ericharper We are pinning this due to issues with tutorial, i believe main branch should also be pinned for the time being while we discuss with PTL how to resolve this safely.

**Comment by artbataev** [comment]
@titu1994 It seem to be a know issue, hope will be fixed soon https://github.com/Lightning-AI/utilities/issues/196

**Comment by titu1994** [comment]
Merging for now - fyi @ericharper @athitten

**Comment by titu1994** [comment]
Don't merge this to main for now (unless Eric or @athitten gives the go ahead for main)

**Comment by artbataev** [comment]
@titu1994 The issue is fixed in Lightning-Utilities in `main`, waiting for the next release: https://github.com/Lightning-AI/utilities/pull/210

**Pull request merged**
