### PR TITLE
Ensure tokens-in-batch is always an upper bound

### PR DESCRIPTION
**Pull request by gabrielbretschner**
# What does this PR do ?

This PR fixes an edge case where a batch may contain more tokens than allowed by `tokens-in-batch`

**Collection**: NLP

# Changelog 
- In case a batch that contains too many tokens has fewer than 8 sentences the last sentence is evicted to a new batch to ensure we don't break the `tokens-in-batch` bound
- Before it would not evict any sentence leading to batches that are too big.

**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

### CODE REVIEW

**Comment by gabrielbretschner** [comment]
I'd really like to get a review. Maybe @MaximumEntropy?

**Review by AlexGrinch — APPROVED** [review]

**Comment by MaximumEntropy** [comment]
@gabrielbretschner thanks for the contribution. Can you please add the appropriate license header to your unittest file?

**Review by PeganovAnton — CHANGES_REQUESTED** [review]
Could you please move the test into `tests/collections/nlp`?

**Comment by gabrielbretschner** [comment]
@MaximumEntropy Added the Licence header to the test file.

**Comment by Numeri** [comment]
@AlexGrinch @MaximumEntropy Any way we could get this fix merged?

**Comment by gabrielbretschner** [comment]
@MaximumEntropy @AlexGrinch Is there anything I can do to get this merged?

**Pull request closed without merging**
