### PR TITLE
Add CharParser for Cyrillic letters

### PR DESCRIPTION
**Pull request by karpov-nick**
Signed-off-by: Карпов Николай Вячеславович <karpnv@yandex.ru>

# What does this PR do ?

Add RUCharParser to parse Cyrillic letters

**Collection**: ASR collection

# Changelog 
- Add RUCharParser to parse Cyrillic letters
- Add config with cyrillic letters examples/asr/conf/quartznet/quartznet_15x5_ru.yaml
- Use RUCharParser as "parser: ru" in train_ds, validation_ds, test_ds

# Usage
* With quartznet_15x5_ru.yaml you can train acoustic model using Golos dataset 

```python
# python3 examples/asr/asr_ctc/speech_to_text_ctc.py -cn quartznet/quartznet_15x5_ru.yaml
```

### CODE REVIEW

**Review by titu1994 — COMMENTED** [review]
This looks like a great contribution ! Since I don't read/write Cyrillic characters, I'll request @okuchaiev for a review ti make sure the chars seem good.

**Review by okuchaiev — APPROVED** [review]
lgtm

**Comment by titu1994** [comment]
Hi, can you run the style fix and commit again? Run python setup.py style --fix --scope=nemo

**Review by titu1994 — DISMISSED** [review]

**Comment by titu1994** [comment]
Hmm seems style is an issue - 

```
Running style
Running command: isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=119 -rc -ws . --check --diff
Skipped 4 files
Running command: black --skip-string-normalization --line-length=119 . --check --diff
--- nemo/collections/common/parts/preprocessing/parsers.py	2022-05-04 06:39:04.516004 +0000
+++ nemo/collections/common/parts/preprocessing/parsers.py	2022-05-04 06:39:30.345561 +0000
@@ -207,28 +207,22 @@
 
     def _normalize(self, text: str) -> Optional[str]:
         # noinspection PyBroadException
         try:
             text = cleaners.clean_text(
-                string=text,
-                table=self._table,
-                punctuation_to_replace=self.PUNCTUATION_TO_REPLACE,
+                string=text, table=self._table, punctuation_to_replace=self.PUNCTUATION_TO_REPLACE,
             )
         except Exception:
             return None
 
         return text
 
 
 NAME_TO_PARSER = frozendict.frozendict({'base': CharParser, 'en': ENCharParser, 'ru': RUCharParser})
 
 
-def make_parser(
-    labels: Optional[List[str]] = None,
-    name: str = 'base',
-    **kwargs,
-) -> CharParser:
+def make_parser(labels: Optional[List[str]] = None, name: str = 'base', **kwargs,) -> CharParser:
     """Creates parser from labels, set of arguments and concise parser name.
 
     Args:
         labels: List of labels to allocate indexes for. If set to
             None then labels would be ascii table list. Essentially, this is a
would reformat nemo/collections/common/parts/preprocessing/parsers.py
Oh no! 💥 💔 💥
1 file would be reformatted, 1284 files would be left unchanged.
```

**Comment by karpov-nick** [comment]
I update black and isort tools and fix stile again

**Review by titu1994 — APPROVED** [review]
Thanks, merged !

**Pull request merged**
