### PR TITLE
Implement getKneighborsConnections better

### PR DESCRIPTION
**Pull request by kimdwkimdw**
Signed-off-by: Dongwoo Arthur Kim <kimdwkimdw@gmail.com>

# What does this PR do ?

Removing `for statement` and optimizing `getKneighborsConnections`

# Changelog 
- https://github.com/NVIDIA/NeMo/pull/5976/files#diff-4188601503d6fb6ce4e990e5148c6c02e57660f95043a149b69b485d492c68b6L314-R318
  - Just simple optimized operation

# Usage
Nothing to be different as before.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [x] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [x] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

This is a part of ASR, diarizer.
@titu1994 @redoctopus, @jbalam-nv, or @okuchaiev

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by kimdwkimdw** [comment]
Anyone? @titu1994 @redoctopus, @jbalam-nv, or @okuchaiev

**Comment by kimdwkimdw** [comment]
stale tag attached. @tango4j

**Comment by tango4j** [comment]
Hi, Sorry that I checked this PR so late.
Thank you so much for doing this PR.
I have added some mask method other than binarization methods.
in the original paper, 'binary' method is used but there are multiple reports that 'drop' method works better (for example, in Kaldi implementation of NMESC it is)
Also added unit test for `getKneighborsConnections` function.

I am having 3~5x of speed up in clustering, with V100 GPU. I wonder how faster it is after batch sorting on your end.

Please share your thoughts, and if there is no problem, I will approve.

**Comment by kimdwkimdw** [comment]
I didn't know there were multiple methods in the original paper.

My only concern, albeit small, is the `.half()` function. Do all the other functions that call the `getKneighborsConnections` function also use half()?

This could create unnecessary type conversions.

**Comment by tango4j** [comment]
> @tango4j It's really happy to hear `a great contribution` and you can feel noticeable improvements. (3~5x speed up in clustering)
> 
> I didn't know there were multiple methods in the original paper.
> 
> My only concern, albeit small, is the `.half()` function. Do all the other functions that call the `getKneighborsConnections` function also use half()?
> 
> This could create unnecessary type conversions.

@kimdwkimdw 
The thing that I didn't mention is this function needs to be passing the compile process after attaching `@torch.jit.script` decorator. I am not sure it happens all the time, but I remember torch.jit.script export sometimes not allow `.float()`.

If this is your concern, change everything to float() and see if it passes this line in the test:

https://github.com/NVIDIA/NeMo/blob/10ceb1c053e6bc5f407412780a4afe8f8f492393/tests/collections/asr/test_diar_utils.py#L463

But using float32 would increase the memory usage and this is a big deal when diarizing a long audio file (2~3 hours).

**Comment by kimdwkimdw** [comment]
OK, agree.
Then, `getAffinityGraphMat`, `getMinimumConnection`and remainders will use float16.

I did `git rebase` with all commits for `Signed-off-by`

**Pull request merged**
