### PR TITLE
Update NFA video download link

### PR DESCRIPTION
**Pull request by erastorgueva-nv**
# What does this PR do ?
Update the link used to download the video we use in the NFA tutorial.

**Collection**: tutorials

# Changelog 
- Update link in the 2 places it appears in the notebook.

# Usage
N/A

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ N/A ] Did you write any new necessary tests?
- [ N/A ] Did you add or update any necessary documentation?
- [ N/A ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Review by nithinraok — APPROVED** [review]
LGTM

**Comment by erastorgueva-nv** [comment]
jenkins

**Comment by erastorgueva-nv** [comment]
jenkins

**Comment by erastorgueva-nv** [comment]
jenkins

**Pull request merged**
