### PR TITLE
unifying to extract mel spectrogram using nemo.collections.asr.module…

### PR DESCRIPTION
**Pull request by XuesongYang**
# What does this PR do ?

unifying to extract mel spectrogram using `nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor`.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

### CODE REVIEW

**Comment by blisc** [comment]
Renaming `nfilts` to `features` will likely cause a lot of older checkpoints to break. Thoughts @titu1994

**Review by titu1994 — CHANGES_REQUESTED** [review]
Do not change nfilt to features - why is this necessary ?

**Comment by subhankar-ghosh** [comment]
LGTM other than the renaming part. I don't think renaming should be done either.

**Comment by XuesongYang** [comment]
Thank you guys for your time reviewing my PR. After diving deep, it looks like I don't have confidence to either decouple or unify the two for now. For example, `FilterbankFeatures` uses `nfilt` and `AudioToMelSpectrogramPreprocessor` uses `features` although the meanings are the same; `FilterbankFeatures` supports `use_grad` by default, while `AudioToMelSpectrogramPreprocessor` does not support it explicitly but implicitly false it by calling `FilterbankFeatures`. Let's de-prioritize this PR for now.

**Comment by titu1994** [comment]
Oh I'd forgotten about the gradient stopping of the asr wrapper. Hmm no wonder my experiments didn't work. Good catch. 

Agreed, let's skip this pr for now. We can introduce it if / when we have a major release of Nemo that will allow breaking changes

**Pull request closed without merging**
